/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> =
  ArrayTypeImpl<T> extends (infer U)[] ? U[] : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S[], I[], U[]>
    : T[];

export type AuthenticationColorScheme = "dark" | "light" | "system";

export type AuthenticationPkceChallengeMethod = "S256";

export type AuthenticationUserRole = "admin" | "adult" | "child" | "guest";

export type AuthenticationWebauthnTransport =
  | "ble"
  | "cable"
  | "hybrid"
  | "internal"
  | "nfc"
  | "smart-card"
  | "usb";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LanguageType =
  | "constructed"
  | "extinct"
  | "historical"
  | "living"
  | "special";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Asset {
  checksum: Buffer;
  created_at: Generated<Timestamp>;
  created_by: Int8 | null;
  edition_id: Int8;
  filename: string;
  id: Generated<Int8>;
  media_type: string;
  metadata: Generated<Json>;
  size: number;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
}

export interface AuthenticationAccessToken {
  client_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  revoked_at: Timestamp | null;
  scopes: string[];
  /**
   * The access token value.
   */
  token: string;
  /**
   * User ID the access token belongs to. Will be NULL for service tokens.
   */
  user_id: Int8 | null;
}

export interface AuthenticationAuthenticator {
  agent: string | null;
  backed_up: Generated<boolean>;
  counter: Generated<Int8>;
  created_at: Generated<Timestamp>;
  device_type: string;
  handle: string | null;
  id: Generated<Int8>;
  identifier: string;
  last_used_at: Timestamp | null;
  public_key: string;
  transports: ArrayType<AuthenticationWebauthnTransport>;
  type: string | null;
  updated_at: Timestamp | null;
  user_id: Int8;
}

export interface AuthenticationAuthorizationCode {
  /**
   * The PKCE code challenge associated with the authorization code.
   */
  challenge: string;
  challenge_method: Generated<AuthenticationPkceChallengeMethod>;
  client_id: string;
  /**
   * Actual authorization code value.
   */
  code: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  /**
   * Redirect URI where the response will be sent.
   */
  redirect_uri: string;
  /**
   * Whether this authorization code has been revoked and cannot be used anymore.
   */
  revoked: Generated<boolean>;
  /**
   * Effective OAuth scopes granted by the user to the client which generated this authorization code.
   */
  scopes: string[];
  /**
   * Timestamp when this authorization code has been used by a client to issue an access token, and thus cannot be used anymore.
   */
  used_at: Timestamp | null;
  user_id: Int8;
}

export interface AuthenticationAuthorizationRequest {
  client_id: string;
  code_challenge: string;
  code_challenge_method: string;
  created_at: Generated<Timestamp>;
  /**
   * TImestamp the authorization request expires.
   */
  expires_at: Timestamp;
  id: Generated<Int8>;
  identifier: Generated<string>;
  redirect_uri: string;
  response_type: string;
  scopes: string[] | null;
  state: string | null;
  /**
   * Timestamp the authorization request has been used.
   */
  used_at: Timestamp | null;
}

export interface AuthenticationChallenge {
  challenge: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  session_identifier: string;
}

export interface AuthenticationClient {
  /**
   * Whether the client is in active use. Inactive clients will not be able to issue access tokens.
   */
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  description: string | null;
  /**
   * Alphanumeric ID of the client.
   */
  id: string;
  name: string | null;
  /**
   * Whether this client is only available to its owner. Must be FALSE for system clients.
   */
  personal: Generated<boolean>;
  /**
   * OAuth Redirect URIs registered for this client. A server-side client must not have any redirect URIs, otherwise it cannot be used with the client_credentials grant.
   */
  redirect_uris: string[] | null;
  /**
   * Whether the client has been revoked. Any token or authorization code issued by the client will also be regarded as revoked.
   */
  revoked: Generated<boolean>;
  /**
   * OAuth client secret for this client. Must be NULL unless intended for server-side clients (which may only use the client_credentials grant type).
   */
  secret: string | null;
  updated_at: Timestamp | null;
  /**
   * Owner of this client. Must be NULL for system clients, which cannot be modified in the user interface and will skip the permission dialogs.
   */
  user_id: Int8 | null;
}

export interface AuthenticationClientScope {
  client_id: string;
  scope_id: string;
}

export interface AuthenticationDeviceChallenge {
  /**
   * Whether the challenge has been approved by the user (true), denied (false), or is still pending (NULL).
   */
  approved: boolean | null;
  /**
   * ID of the client that created the challenge.
   */
  client_id: string;
  /**
   * Creation time of this device challenge.
   */
  created_at: Generated<Timestamp>;
  /**
   * Verification code for this challenge as generated by the authorization server.
   */
  device_code: string;
  /**
   * Expiration time of this device challenge.
   */
  expires_at: Timestamp;
  id: Generated<Int8>;
  /**
   * Last time the client has polled for the current challenge status, used to prevent abuse. Will be NULL if the client has not polled yet.
   */
  last_poll_at: Timestamp | null;
  /**
   * Optional set of scopes requested by the client for this specific challenge. Only used if a subset of the available client scopes is provided.
   */
  scopes: string[] | null;
  /**
   * Timestamp when the device code has been used to issue an access token, and thus cannot be used anymore.
   */
  used_at: Timestamp | null;
  /**
   * Verification code the user has to enter on the device screen; should be short (usually 6-8 numbers and/or letters). Maximum of 8 characters for usability reasons.
   */
  user_code: string;
}

export interface AuthenticationPasscode {
  code: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  user_id: Int8;
}

export interface AuthenticationRefreshToken {
  client_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  revoked_at: Timestamp | null;
  scopes: string[];
  token: string;
  /**
   * User ID the refresh token belongs to. Will be NULL for service tokens.
   */
  user_id: Int8 | null;
}

export interface AuthenticationScope {
  created_at: Generated<Timestamp>;
  description: string | null;
  /**
   * Name of the scope. Must
   */
  id: string;
  /**
   * Whether this scope is only available to server-side client integrations using the client_credentials grant.
   */
  server: Generated<boolean>;
}

export interface AuthenticationUser {
  /**
   * The birthdate of a user. This is used to automatically apply age restrictions, if the user has the child role.
   */
  birthdate: Timestamp | null;
  /**
   * Preferred color scheme to display the application in.
   */
  color_scheme: Generated<AuthenticationColorScheme | null>;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<Int8>;
  name: string | null;
  /**
   * The authorization role of a user.
   */
  role: Generated<AuthenticationUserRole>;
  updated_at: Timestamp | null;
  verified: Generated<boolean>;
}

export interface AuthenticationUserConsent {
  client_id: string;
  /**
   * Timestamp of consent expiration. To avoid indefinitely granting consent to a client, users have to reconfirm their choices after a given amount of time.
   */
  expires_at: Timestamp;
  /**
   * Timestamp the user has granted consent to the client.
   */
  granted_at: Generated<Timestamp>;
  /**
   * Timestamp the user revoked their consent for the client. Effectively the same as having never given consent at all. If NULL, the user did not revoke their consent yet.
   */
  revoked_at: Timestamp | null;
  /**
   * Scopes the user has granted the client to use at the time of consent.
   */
  scopes: string[];
  user_id: Generated<Int8>;
}

export interface Book {
  created_at: Generated<Timestamp>;
  created_by: Int8 | null;
  id: Generated<Int8>;
  /**
   * The main, or preferred, edition of a book. Represents the book in listings and collections.
   */
  main_edition_id: Int8 | null;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
}

export interface BookComment {
  book_id: Generated<Int8>;
  comment_id: Int8;
}

export interface BookRating {
  book_id: Generated<Int8>;
  created_at: Generated<Timestamp>;
  rating: number;
  user_id: Int8;
}

export interface BookTag {
  book_id: Generated<Int8>;
  tag_id: Int8;
}

export interface Catalog {
  /**
   * Whether this catalog is currently active and used in the app.
   */
  active: Generated<boolean>;
  /**
   * The minimum required age to access this catalog
   */
  age_requirement: Generated<number>;
  color: string | null;
  created_at: Generated<Timestamp>;
  credentials_required: Generated<boolean>;
  /**
   * Description of this feed; usually retrieved from the summary entry of the feed itself.
   */
  description: string | null;
  /**
   * The OPDS feed URL to retrieve this catalog.
   */
  feed_url: string;
  id: Generated<Int8>;
  /**
   * An optional URL to an image representing the feed; usually retrieved from the thumbnail image link of the feed itself.
   */
  image_url: string | null;
  /**
   * Name of this feed; usually retrieved from the title entry of the feed itself.
   */
  title: string | null;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
  /**
   * The website of the feed provider.
   */
  url: string | null;
}

export interface Collection {
  /**
   * Minimum age in years users must reach to access this collection. This obviously will only work if a birthdate has been set for a user.
   */
  age_requirement: Generated<number>;
  /**
   * Optional hex color to tint this collection. Does not allow transparency (which will be applied by the application).
   */
  color: Buffer | null;
  created_at: Generated<Timestamp>;
  created_by: Int8 | null;
  /**
   * Optional long-form description of this collection formatted as Markdown.
   */
  description: string | null;
  /**
   * Optional emoji to represent this collection, acting as an icon.
   */
  emoji: string | null;
  id: Generated<Int8>;
  /**
   * Mandatory collection name. Must be less than 150 characters.
   */
  name: string;
  /**
   * Shared collections are accessible by all users; personal collections (shared is false) are only visible to the user who created them.
   */
  shared: Generated<boolean>;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
}

export interface CollectionComment {
  collection_id: Generated<Int8>;
  comment_id: Int8;
}

export interface CollectionEntry {
  /**
   * Reference to the book this entry refers to. Unless a specific edition is referenced in `edition_id`, the main edition will be used.
   */
  book_id: Int8;
  collection_id: Int8;
  created_at: Generated<Timestamp>;
  created_by: Int8 | null;
  /**
   * Optional specific edition of a book to add. This is useful to create a collection of audio books, for example. If not set, the main edition of the book will be used.
   */
  edition_id: Int8;
  /**
   * Order position of the collection entry. Applies to all users. To change the position, a reordering of all other collection entries is required.
   */
  position: number;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
}

export interface CollectionTag {
  collection_id: Generated<Int8>;
  tag_id: Int8;
}

export interface Comment {
  content: string;
  created_at: Generated<Timestamp>;
  created_by: Int8 | null;
  id: Generated<Int8>;
  updated_at: Timestamp | null;
}

export interface CommentReaction {
  comment_id: Int8;
  created_at: Generated<Timestamp>;
  emoji: string;
  user_id: Int8;
}

export interface Contribution {
  /**
   * Reference to a creator that contributed to the given edition of a book.
   */
  creator_id: Int8;
  /**
   * Reference to an edition of a book the given creator contributed to.
   */
  edition_id: Int8;
  /**
   * Whether the contribution should be considered essential to the edition; non-essential contributors may not be displayed at all times.
   */
  essential: Generated<boolean>;
  /**
   * The kind of contribution the creator made to the given book edition, e.g. "authored", "illustrated", or "co-authored".
   */
  type: string | null;
}

export interface Cover {
  /**
   * A blurhash representation of the image; see https://blurha.sh/. Blurhashes are simple string representations of an image that can be used to render a blurred approximation of the original image.
   */
  blurhash: string;
  /**
   * An SHA1 hash of the file, used for ETag headers and sanity checks.
   */
  checksum: Buffer;
  created_at: Generated<Timestamp>;
  created_by: Int8 | null;
  /**
   * A human-readable description of the image intended for visually impaired users.
   */
  description: string | null;
  /**
   * Name, or key, of the file as persisted to the storage bucket.
   */
  filename: string;
  /**
   * Height of the image, in pixels.
   */
  height: number;
  id: Generated<Int8>;
  /**
   * A media type string describing the type of image file (e.g. "image/png" for a PNG file).
   */
  media_type: string;
  /**
   * JSON object containing image file metadata.
   */
  metadata: Generated<Json>;
  /**
   * Size of the file, in bytes.
   */
  size: number;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
  /**
   * Width of the image, in pixels.
   */
  width: number;
}

export interface CoverCreator {
  cover_id: Generated<Int8>;
  creator_id: Int8;
  essential: Generated<boolean>;
}

export interface Creator {
  amazon_id: string | null;
  created_at: Generated<Timestamp>;
  /**
   * Description, or biography, of a creator (e.g. an author). Free-text, providing more information on a given creator. Should be provided as Markdown.
   */
  description: string | null;
  goodreads_id: string | null;
  id: Generated<Int8>;
  image: string | null;
  /**
   * Full name of the creator.
   */
  name: string;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
  /**
   * Link to the website operated by, or another location on the internet representative of, the creator.
   */
  url: string | null;
  wikipedia_url: string | null;
}

export interface CreatorComment {
  comment_id: Int8;
  creator_id: Generated<Int8>;
}

export interface Edition {
  /**
   * Type of binding of this edition of the book (e.g. "hardcover").
   */
  binding: string | null;
  book_id: Int8 | null;
  cover_id: Int8 | null;
  created_at: Generated<Timestamp>;
  /**
   * An excerpt from the content of the book.
   */
  excerpt: string | null;
  format: string | null;
  id: Generated<Int8>;
  /**
   * Legacy ISBN-10 identifier of this edition of the book.
   */
  isbn_10: string | null;
  /**
   * Modern ISBN-13 identifier of this edition of the book.
   */
  isbn_13: string | null;
  language: string | null;
  /**
   * Any legal information associated with this edition of a book, for example on copyright holders or usage permissions.
   */
  legal_information: string | null;
  /**
   * Number of pages in this edition of the book.
   */
  pages: number | null;
  /**
   * Date the edition of the book has been published.
   */
  published_at: Timestamp | null;
  /**
   * Reference to the publisher of this edition of the book.
   */
  publisher_id: Int8 | null;
  /**
   * A version of the book title intended to used for sorting a list of books (e.g. "Prisoner of Azkaban, the").
   */
  sorting_key: string | null;
  /**
   * Synopsis of this edition of the book.
   */
  synopsis: string | null;
  /**
   * Title of this edition of the book.
   */
  title: string;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
}

export interface Language {
  iso_639_1: string | null;
  iso_639_3: string;
  name: string | null;
  type: LanguageType;
}

export interface Publisher {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<Int8>;
  image: string | null;
  name: string;
  sorting_key: string;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
  url: string | null;
  wikipedia_url: string | null;
}

export interface PublisherComment {
  comment_id: Int8;
  publisher_id: Generated<Int8>;
}

export interface Review {
  /**
   * Full content of the review, formatted as Markdown.
   */
  content: string;
  created_at: Generated<Timestamp>;
  /**
   * Reference to the edition of a book this review refers to.
   */
  edition_id: Int8;
  /**
   * An excerpt from the full review as provided in content. Must not be longer than 200 characters.
   */
  excerpt: string | null;
  id: Generated<Int8>;
  /**
   * Name of the publication the review has been published in (e.g. "New York Times", "NPR").
   */
  publication_name: string | null;
  /**
   * Date the review has been published.
   */
  published_at: Timestamp | null;
  /**
   * Reference to an existing creator that published the review. This is useful for reviews by another author, for example.
   */
  reviewer_id: Int8 | null;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
  /**
   * URL of the page the review has been published at.
   */
  url: string | null;
}

export interface Series {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  language: string | null;
  /**
   * Name of the series of books.
   */
  name: string | null;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
}

export interface SeriesComment {
  comment_id: Int8 | null;
  series_id: Generated<Int8>;
}

export interface SeriesEntry {
  book_id: Generated<Int8>;
  /**
   * Position of the given boko in the series.
   */
  position: number | null;
  series_id: Int8;
}

export interface SeriesTag {
  series_id: Generated<Int8>;
  tag_id: Int8;
}

export interface Settings {
  created_at: Timestamp | null;
  data: Json | null;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
  version: number | null;
}

export interface SettingsRevision {
  created_at: Generated<Timestamp>;
  data: Json;
  updated_at: Generated<Timestamp>;
  updated_by: Int8 | null;
  version: number;
}

export interface Tag {
  color: string | null;
  created_at: Generated<Timestamp>;
  created_by: Int8 | null;
  emoji: string | null;
  id: Generated<Int8>;
  value: string;
}

export interface UserCollectionFavorite {
  collection_id: Int8;
  user_id: Generated<Int8>;
}

export interface UserCreatorFavorite {
  creator_id: Int8;
  user_id: Generated<Int8>;
}

export interface DB {
  asset: Asset;
  "authentication.access_token": AuthenticationAccessToken;
  "authentication.authenticator": AuthenticationAuthenticator;
  "authentication.authorization_code": AuthenticationAuthorizationCode;
  "authentication.authorization_request": AuthenticationAuthorizationRequest;
  "authentication.challenge": AuthenticationChallenge;
  "authentication.client": AuthenticationClient;
  "authentication.client_scope": AuthenticationClientScope;
  "authentication.device_challenge": AuthenticationDeviceChallenge;
  "authentication.passcode": AuthenticationPasscode;
  "authentication.refresh_token": AuthenticationRefreshToken;
  "authentication.scope": AuthenticationScope;
  "authentication.user": AuthenticationUser;
  "authentication.user_consent": AuthenticationUserConsent;
  book: Book;
  book_comment: BookComment;
  book_rating: BookRating;
  book_tag: BookTag;
  catalog: Catalog;
  collection: Collection;
  collection_comment: CollectionComment;
  collection_entry: CollectionEntry;
  collection_tag: CollectionTag;
  comment: Comment;
  comment_reaction: CommentReaction;
  contribution: Contribution;
  cover: Cover;
  cover_creator: CoverCreator;
  creator: Creator;
  creator_comment: CreatorComment;
  edition: Edition;
  language: Language;
  publisher: Publisher;
  publisher_comment: PublisherComment;
  review: Review;
  series: Series;
  series_comment: SeriesComment;
  series_entry: SeriesEntry;
  series_tag: SeriesTag;
  settings: Settings;
  settings_revision: SettingsRevision;
  tag: Tag;
  user_collection_favorite: UserCollectionFavorite;
  user_creator_favorite: UserCreatorFavorite;
  "vault.decrypted_secrets": VaultDecryptedSecrets;
  "vault.secrets": VaultSecrets;
  work: Work;
  work_comment: WorkComment;
  work_rating: WorkRating;
  work_tag: WorkTag;
}
