/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> =
  ArrayTypeImpl<T> extends (infer U)[] ? U[] : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S[], I[], U[]>
    : T[];

export type AuthenticationColorScheme = "dark" | "light" | "system";

export type AuthenticationPkceChallengeMethod = "S256";

export type AuthenticationUserRole = "admin" | "adult" | "child" | "guest";

export type AuthenticationWebauthnTransport =
  | "ble"
  | "cable"
  | "hybrid"
  | "internal"
  | "nfc"
  | "smart-card"
  | "usb";

export type ContributionRole =
  | "abr"
  | "acp"
  | "act"
  | "adi"
  | "adp"
  | "aft"
  | "anc"
  | "anl"
  | "anm"
  | "ann"
  | "ant"
  | "ape"
  | "apl"
  | "app"
  | "aqt"
  | "arc"
  | "ard"
  | "arr"
  | "art"
  | "asg"
  | "asn"
  | "ato"
  | "att"
  | "auc"
  | "aud"
  | "aue"
  | "aui"
  | "aup"
  | "aus"
  | "aut"
  | "bdd"
  | "bjd"
  | "bka"
  | "bkd"
  | "bkp"
  | "blw"
  | "bnd"
  | "bpd"
  | "brd"
  | "brl"
  | "bsl"
  | "cad"
  | "cas"
  | "ccp"
  | "chr"
  | "cli"
  | "cll"
  | "clr"
  | "clt"
  | "cmm"
  | "cmp"
  | "cmt"
  | "cnd"
  | "cng"
  | "cns"
  | "coe"
  | "col"
  | "com"
  | "con"
  | "cop"
  | "cor"
  | "cos"
  | "cot"
  | "cou"
  | "cov"
  | "cpc"
  | "cpe"
  | "cph"
  | "cpl"
  | "cpt"
  | "cre"
  | "crp"
  | "crr"
  | "crt"
  | "csl"
  | "csp"
  | "cst"
  | "ctb"
  | "cte"
  | "ctg"
  | "ctr"
  | "cts"
  | "ctt"
  | "cur"
  | "cwt"
  | "dbd"
  | "dbp"
  | "dfd"
  | "dfe"
  | "dft"
  | "dgc"
  | "dgg"
  | "dgs"
  | "dis"
  | "djo"
  | "dln"
  | "dnc"
  | "dnr"
  | "dpc"
  | "dpt"
  | "drm"
  | "drt"
  | "dsr"
  | "dst"
  | "dtc"
  | "dte"
  | "dtm"
  | "dto"
  | "dub"
  | "edc"
  | "edd"
  | "edm"
  | "edt"
  | "egr"
  | "elg"
  | "elt"
  | "eng"
  | "enj"
  | "etr"
  | "evp"
  | "exp"
  | "fac"
  | "fds"
  | "fld"
  | "flm"
  | "fmd"
  | "fmk"
  | "fmo"
  | "fmp"
  | "fnd"
  | "fon"
  | "fpy"
  | "frg"
  | "gdv"
  | "gis"
  | "his"
  | "hnr"
  | "hst"
  | "ill"
  | "ilu"
  | "ins"
  | "inv"
  | "isb"
  | "itr"
  | "ive"
  | "ivr"
  | "jud"
  | "jug"
  | "lbr"
  | "lbt"
  | "ldr"
  | "led"
  | "lee"
  | "lel"
  | "len"
  | "let"
  | "lgd"
  | "lie"
  | "lil"
  | "lit"
  | "lsa"
  | "lse"
  | "lso"
  | "ltg"
  | "ltr"
  | "lyr"
  | "mcp"
  | "mdc"
  | "med"
  | "mfp"
  | "mfr"
  | "mka"
  | "mod"
  | "mon"
  | "mrb"
  | "mrk"
  | "msd"
  | "mte"
  | "mtk"
  | "mup"
  | "mus"
  | "mxe"
  | "nan"
  | "nrt"
  | "onp"
  | "opn"
  | "org"
  | "orm"
  | "osp"
  | "oth"
  | "own"
  | "pad"
  | "pan"
  | "pat"
  | "pbd"
  | "pbl"
  | "pdr"
  | "pfr"
  | "pht"
  | "plt"
  | "pma"
  | "pmn"
  | "pop"
  | "ppm"
  | "ppt"
  | "pra"
  | "prc"
  | "prd"
  | "pre"
  | "prf"
  | "prg"
  | "prm"
  | "prn"
  | "pro"
  | "prp"
  | "prs"
  | "prt"
  | "prv"
  | "pta"
  | "pte"
  | "ptf"
  | "pth"
  | "ptt"
  | "pup"
  | "rap"
  | "rbr"
  | "rcd"
  | "rce"
  | "rcp"
  | "rdd"
  | "red"
  | "ren"
  | "res"
  | "rev"
  | "rpc"
  | "rps"
  | "rpt"
  | "rpy"
  | "rse"
  | "rsg"
  | "rsp"
  | "rsr"
  | "rst"
  | "rth"
  | "rtm"
  | "rxa"
  | "sad"
  | "sce"
  | "scl"
  | "scr"
  | "sde"
  | "sds"
  | "sec"
  | "sfx"
  | "sgd"
  | "sgn"
  | "sht"
  | "sll"
  | "sng"
  | "spk"
  | "spn"
  | "spy"
  | "srv"
  | "std"
  | "stg"
  | "stl"
  | "stm"
  | "stn"
  | "str"
  | "swd"
  | "tau"
  | "tcd"
  | "tch"
  | "ths"
  | "tld"
  | "tlg"
  | "tlh"
  | "tlp"
  | "trc"
  | "trl"
  | "tyd"
  | "tyg"
  | "uvp"
  | "vac"
  | "vdg"
  | "vfx"
  | "wac"
  | "wal"
  | "wam"
  | "wat"
  | "wdc"
  | "wde"
  | "wfs"
  | "wft"
  | "win"
  | "wit"
  | "wpr"
  | "wst"
  | "wts";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LanguageType =
  | "constructed"
  | "extinct"
  | "historical"
  | "living"
  | "special";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Asset {
  checksum: Buffer;
  created_at: Generated<Timestamp>;
  created_by: Int8 | null;
  edition_id: Int8;
  filename: string;
  id: Generated<Int8>;
  media_type: string;
  metadata: Generated<Json>;
  /**
   * Error message if search indexing failed for this asset.
   */
  search_index_error: string | null;
  /**
   * Timestamp when the asset was last indexed for full-text search.
   */
  search_indexed_at: Timestamp | null;
  size: number;
  storage_reference: string;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
}

export interface AuthenticationAccessToken {
  client_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  revoked_at: Timestamp | null;
  scopes: string[];
  token: string;
  user_id: Int8 | null;
}

export interface AuthenticationApiKey {
  created_at: Generated<Timestamp>;
  /**
   * Optional expiration timestamp. NULL means the key never expires.
   */
  expires_at: Timestamp | null;
  id: Generated<Int8>;
  /**
   * SHA-256 hash of the API key. The plain text key is never stored.
   */
  key_hash: string;
  /**
   * First 12 characters of the key (col_ + 8 chars) for identification in logs and UI.
   */
  key_prefix: string;
  /**
   * Timestamp of last successful authentication with this key.
   */
  last_used_at: Timestamp | null;
  /**
   * IP address from which the key was last used.
   */
  last_used_ip: string | null;
  /**
   * User-provided name to identify this key (e.g., "Kindle", "Reading Script").
   */
  name: string;
  /**
   * Timestamp when the key was revoked. NULL means the key is active.
   */
  revoked_at: Timestamp | null;
  /**
   * Timestamp when this key was rotated. Used for 15-minute grace period.
   */
  rotated_at: Timestamp | null;
  /**
   * Reference to the previous key if this was created by rotation.
   */
  rotated_from_id: Int8 | null;
  /**
   * Permission scopes granted to this key. Empty array means all scopes.
   */
  scopes: Generated<string[]>;
  /**
   * User who owns this API key.
   */
  user_id: Int8;
}

export interface AuthenticationAuthenticator {
  agent: string | null;
  backed_up: Generated<boolean>;
  counter: Generated<Int8>;
  created_at: Generated<Timestamp>;
  device_type: string;
  handle: string | null;
  id: Generated<Int8>;
  identifier: string;
  last_used_at: Timestamp | null;
  public_key: string;
  transports: ArrayType<AuthenticationWebauthnTransport>;
  type: string | null;
  updated_at: Timestamp | null;
  user_id: Int8;
}

export interface AuthenticationAuthorizationCode {
  challenge: string;
  challenge_method: Generated<AuthenticationPkceChallengeMethod>;
  client_id: string;
  code: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  redirect_uri: string;
  revoked: Generated<boolean>;
  scopes: string[];
  used_at: Timestamp | null;
  user_id: Int8;
}

export interface AuthenticationAuthorizationRequest {
  client_id: string;
  code_challenge: string;
  code_challenge_method: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  identifier: Generated<string>;
  redirect_uri: string;
  response_type: string;
  scopes: string[] | null;
  state: string | null;
  used_at: Timestamp | null;
}

export interface AuthenticationChallenge {
  challenge: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  session_identifier: string;
}

export interface AuthenticationClient {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: string;
  name: string | null;
  personal: Generated<boolean>;
  redirect_uris: string[] | null;
  revoked: Generated<boolean>;
  secret: string | null;
  updated_at: Timestamp | null;
  user_id: Int8 | null;
}

export interface AuthenticationClientScope {
  client_id: string;
  scope_id: string;
}

export interface AuthenticationDeviceChallenge {
  approved: boolean | null;
  client_id: string;
  created_at: Generated<Timestamp>;
  device_code: string;
  expires_at: Timestamp;
  id: Generated<Int8>;
  last_poll_at: Timestamp | null;
  scopes: string[] | null;
  used_at: Timestamp | null;
  user_code: string;
}

export interface AuthenticationPasscode {
  code: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  user_id: Int8;
}

export interface AuthenticationRefreshToken {
  client_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  revoked_at: Timestamp | null;
  scopes: string[];
  token: string;
  user_id: Int8 | null;
}

export interface AuthenticationScope {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: string;
  server: Generated<boolean>;
}

export interface AuthenticationUser {
  birthdate: Timestamp | null;
  color_scheme: Generated<AuthenticationColorScheme | null>;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<Int8>;
  name: string | null;
  role: Generated<AuthenticationUserRole>;
  updated_at: Timestamp | null;
  verified: Generated<boolean>;
}

export interface AuthenticationUserConsent {
  client_id: string;
  expires_at: Timestamp;
  granted_at: Generated<Timestamp>;
  revoked_at: Timestamp | null;
  scopes: string[];
  user_id: Generated<Int8>;
}

export interface BookChunk {
  /**
   * Reference to the source asset file this chunk was extracted from.
   */
  asset_id: Int8;
  /**
   * Sequential index of this chunk within the asset, used for ordering.
   */
  chunk_index: number;
  /**
   * Plain text content of this chunk.
   */
  content: string;
  created_at: Generated<Timestamp>;
  /**
   * PostgreSQL full-text search configuration name (e.g., english, german, simple). Denormalized from edition language.
   */
  fts_config: Generated<string>;
  id: Generated<Int8>;
  /**
   * Language-aware full-text search vector for content search queries.
   */
  search_vector: Generated<string | null>;
  /**
   * Location pointer for deep linking to the chunk position in the source file.
   */
  source_pointer: Json;
}

export interface Catalog {
  active: Generated<boolean>;
  age_requirement: Generated<number>;
  color: string | null;
  created_at: Generated<Timestamp>;
  credentials_required: Generated<boolean>;
  description: string | null;
  feed_url: string;
  id: Generated<Int8>;
  image_url: string | null;
  title: string | null;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
  url: string | null;
}

export interface Collection {
  age_requirement: Generated<number>;
  color: Buffer | null;
  created_at: Generated<Timestamp>;
  created_by: Int8 | null;
  description: string | null;
  icon: string | null;
  id: Generated<Int8>;
  like_count: Generated<number>;
  name: string;
  search_vector: Generated<string | null>;
  shared: boolean | null;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
}

export interface CollectionComment {
  collection_id: Generated<Int8>;
  comment_id: Int8;
}

export interface CollectionEntry {
  collection_id: Int8;
  created_at: Generated<Timestamp>;
  created_by: Int8 | null;
  edition_id: Int8;
  position: number;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
  work_id: Int8;
}

export interface CollectionTag {
  collection_id: Generated<Int8>;
  tag_id: Int8;
}

export interface Comment {
  content: string;
  created_at: Generated<Timestamp>;
  created_by: Int8 | null;
  hidden_at: Timestamp | null;
  hidden_by: Int8 | null;
  hidden_reason: string | null;
  id: Generated<Int8>;
  parent_comment_id: Int8 | null;
  updated_at: Timestamp | null;
}

export interface CommentReaction {
  comment_id: Int8;
  created_at: Generated<Timestamp>;
  emoji: string;
  user_id: Int8;
}

export interface CommentReport {
  comment_id: Int8;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  reason: string;
  reported_by: Int8;
  resolution: string | null;
  resolved_at: Timestamp | null;
  resolved_by: Int8 | null;
}

export interface Contribution {
  creator_id: Int8;
  edition_id: Int8;
  essential: Generated<boolean>;
  role: Generated<ContributionRole>;
}

export interface Creator {
  amazon_id: string | null;
  birth_date: Timestamp | null;
  created_at: Generated<Timestamp>;
  death_date: Timestamp | null;
  description: string | null;
  goodreads_id: string | null;
  id: Generated<Int8>;
  image_id: Int8 | null;
  name: string;
  openlibrary_id: string | null;
  patreon_id: string | null;
  search_vector: Generated<string | null>;
  sorting_key: string | null;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
  url: string | null;
  wikipedia_url: string | null;
}

export interface CreatorComment {
  comment_id: Int8;
  creator_id: Generated<Int8>;
}

export interface Edition {
  asin: string | null;
  binding: string | null;
  cover_image_id: Int8 | null;
  created_at: Generated<Timestamp>;
  excerpt: string | null;
  format: string | null;
  id: Generated<Int8>;
  isbn_10: string | null;
  isbn_13: string | null;
  language: string | null;
  legal_information: string | null;
  openlibrary_id: string | null;
  pages: number | null;
  published_at: Timestamp | null;
  publisher_id: Int8 | null;
  search_vector: Generated<string | null>;
  sorting_key: string | null;
  synopsis: string | null;
  title: string;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
  work_id: Int8 | null;
}

export interface Image {
  blurhash: string;
  checksum: Buffer;
  created_at: Generated<Timestamp>;
  created_by: Int8 | null;
  description: string | null;
  filename: string;
  height: number;
  id: Generated<Int8>;
  media_type: string;
  metadata: Generated<Json>;
  size: number;
  storage_reference: string;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
  width: number;
}

export interface ImageCreator {
  creator_id: Int8;
  essential: Generated<boolean>;
  image_id: Generated<Int8>;
}

export interface Language {
  /**
   * PostgreSQL full-text search configuration name (e.g., english, german, simple).
   */
  fts_config: Generated<string>;
  iso_639_1: string | null;
  iso_639_3: string;
  name: string | null;
  type: LanguageType;
}

export interface ModerationLog {
  action_type: string;
  created_at: Generated<Timestamp>;
  details: Json | null;
  id: Generated<Int8>;
  performed_by: Int8;
  target_id: Int8;
  target_type: string;
}

export interface Notification {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  link: string | null;
  message: string | null;
  read_at: Timestamp | null;
  source_id: Int8 | null;
  source_type: string | null;
  title: string;
  type: string;
  user_id: Int8;
}

export interface NotificationPreference {
  comment_mentions: Generated<boolean>;
  comment_reactions: Generated<boolean>;
  comment_replies: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  user_id: Int8;
}

export interface PendingIngestion {
  checksum: string;
  created_at: Generated<Timestamp>;
  duplicate_info: Json;
  expires_at: Generated<Timestamp>;
  extracted_metadata: Json;
  id: Generated<string>;
  s3_key: string;
  upload_id: string;
  user_id: Int8;
}

export interface Publisher {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<Int8>;
  image_id: Int8 | null;
  name: string;
  search_vector: Generated<string | null>;
  sorting_key: string;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
  url: string | null;
  wikipedia_url: string | null;
}

export interface PublisherComment {
  comment_id: Int8;
  publisher_id: Generated<Int8>;
}

export interface Review {
  content: string;
  created_at: Generated<Timestamp>;
  edition_id: Int8;
  excerpt: string | null;
  id: Generated<Int8>;
  publication_name: string | null;
  published_at: Timestamp | null;
  reviewer_id: Int8 | null;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
  url: string | null;
}

export interface Series {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  language: string | null;
  name: string | null;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
}

export interface SeriesComment {
  comment_id: Int8 | null;
  series_id: Generated<Int8>;
}

export interface SeriesEntry {
  position: number | null;
  series_id: Int8;
  work_id: Generated<Int8>;
}

export interface SeriesTag {
  series_id: Generated<Int8>;
  tag_id: Int8;
}

export interface Settings {
  created_at: Timestamp | null;
  data: Json | null;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
  version: number | null;
}

export interface SettingsRevision {
  created_at: Generated<Timestamp>;
  data: Json;
  updated_at: Generated<Timestamp>;
  updated_by: Int8 | null;
  version: Generated<number>;
}

export interface Tag {
  color: string | null;
  created_at: Generated<Timestamp>;
  created_by: Int8 | null;
  emoji: string | null;
  id: Generated<Int8>;
  value: string;
}

export interface UserBlock {
  blocked_id: Int8;
  blocker_id: Int8;
  created_at: Generated<Timestamp>;
}

export interface UserCollectionFavorite {
  collection_id: Int8;
  user_id: Generated<Int8>;
}

export interface UserCreatorFavorite {
  creator_id: Int8;
  user_id: Generated<Int8>;
}

export interface VaultDecryptedSecrets {
  created_at: Timestamp | null;
  decrypted_secret: string | null;
  description: string | null;
  id: string | null;
  key_id: string | null;
  name: string | null;
  nonce: Buffer | null;
  secret: string | null;
  updated_at: Timestamp | null;
}

export interface VaultSecrets {
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  id: Generated<string>;
  key_id: Generated<string | null>;
  name: string | null;
  nonce: Generated<Buffer | null>;
  secret: string;
  updated_at: Generated<Timestamp>;
}

export interface Work {
  created_at: Generated<Timestamp>;
  created_by: Int8 | null;
  id: Generated<Int8>;
  main_edition_id: Int8 | null;
  updated_at: Timestamp | null;
  updated_by: Int8 | null;
}

export interface WorkComment {
  comment_id: Int8;
  work_id: Generated<Int8>;
}

export interface WorkRating {
  created_at: Generated<Timestamp>;
  rating: number;
  user_id: Int8;
  work_id: Generated<Int8>;
}

export interface WorkTag {
  tag_id: Int8;
  work_id: Generated<Int8>;
}

export interface DB {
  asset: Asset;
  "authentication.access_token": AuthenticationAccessToken;
  "authentication.api_key": AuthenticationApiKey;
  "authentication.authenticator": AuthenticationAuthenticator;
  "authentication.authorization_code": AuthenticationAuthorizationCode;
  "authentication.authorization_request": AuthenticationAuthorizationRequest;
  "authentication.challenge": AuthenticationChallenge;
  "authentication.client": AuthenticationClient;
  "authentication.client_scope": AuthenticationClientScope;
  "authentication.device_challenge": AuthenticationDeviceChallenge;
  "authentication.passcode": AuthenticationPasscode;
  "authentication.refresh_token": AuthenticationRefreshToken;
  "authentication.scope": AuthenticationScope;
  "authentication.user": AuthenticationUser;
  "authentication.user_consent": AuthenticationUserConsent;
  book_chunk: BookChunk;
  catalog: Catalog;
  collection: Collection;
  collection_comment: CollectionComment;
  collection_entry: CollectionEntry;
  collection_tag: CollectionTag;
  comment: Comment;
  comment_reaction: CommentReaction;
  comment_report: CommentReport;
  contribution: Contribution;
  creator: Creator;
  creator_comment: CreatorComment;
  edition: Edition;
  image: Image;
  image_creator: ImageCreator;
  language: Language;
  moderation_log: ModerationLog;
  notification: Notification;
  notification_preference: NotificationPreference;
  pending_ingestion: PendingIngestion;
  publisher: Publisher;
  publisher_comment: PublisherComment;
  review: Review;
  series: Series;
  series_comment: SeriesComment;
  series_entry: SeriesEntry;
  series_tag: SeriesTag;
  settings: Settings;
  settings_revision: SettingsRevision;
  tag: Tag;
  user_block: UserBlock;
  user_collection_favorite: UserCollectionFavorite;
  user_creator_favorite: UserCreatorFavorite;
  "vault.decrypted_secrets": VaultDecryptedSecrets;
  "vault.secrets": VaultSecrets;
  work: Work;
  work_comment: WorkComment;
  work_rating: WorkRating;
  work_tag: WorkTag;
}
