packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.23.0
  '@fontsource-variable/material-symbols-outlined': ^5.2.8
  '@fontsource/neuton': ^5.2.5
  '@fontsource/titillium-web': ^5.2.5
  '@sveltejs/adapter-auto': ^6.0.0
  '@sveltejs/kit': ^2.20.3
  '@sveltejs/vite-plugin-svelte': ^5.0.3
  '@tailwindcss/vite': ^4.1.1
  '@trpc/client': ^10.45.2
  '@trpc/server': ^10.45.2
  '@types/jsonwebtoken': ^9.0.2
  '@types/node': ^22.14.0
  '@typescript-eslint/eslint-plugin': ^8.28.0
  '@typescript-eslint/parser': ^8.28.0
  '@vitest/coverage-v8': ^3.1.1
  '@vitest/ui': ^3.1.1
  'jsonwebtoken': ^9.0.2
  'eslint': ^9.24.0
  'eslint-config-prettier': ^10.1.1
  'eslint-plugin-svelte': ^3.5.0
  'globals': ^16.0.0
  'prettier': ^3.5.3
  'prettier-plugin-organize-imports': ^4.1.0
  'prettier-plugin-svelte': ^3.3.3
  'prettier-plugin-tailwindcss': ^0.6.11
  'svelte': ^5.25.3
  'svelte-check': ^4.1.5
  'tailwindcss': ^4.0.15
  'tailwind-merge': ^3.1.0
  'typescript': ^5.8.3
  'typescript-eslint': ^8.28.0
  'unbuild': ^3.5.0
  'vite': ^6.2.4
  'vitest': ^3.1.1
  'zod': ^3.24.2

onlyBuiltDependencies:
  - esbuild
  - svelte-preprocess
