packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.27.0
  '@fontsource-variable/material-symbols-outlined': ^5.2.10
  '@fontsource/neuton': ^5.2.5
  '@fontsource/titillium-web': ^5.2.5
  '@sveltejs/adapter-auto': ^6.0.1
  '@sveltejs/kit': ^2.21.1
  '@sveltejs/vite-plugin-svelte': ^5.0.3
  '@tailwindcss/vite': ^4.1.7
  '@trpc/client': ^10.45.2
  '@trpc/server': ^10.45.2
  '@types/jsonwebtoken': ^9.0.2
  '@types/node': ^22.15.21
  '@typescript-eslint/eslint-plugin': ^8.32.0
  '@typescript-eslint/parser': ^8.32.0
  '@vitest/coverage-v8': ^3.1.4
  '@vitest/ui': ^3.1.4
  jsonwebtoken: ^9.0.2
  eslint: ^9.27.0
  esm-env: ^1.2.2
  globals: ^16.1.0
  prettier: ^3.5.3
  rimraf: ^6.0.1
  svelte: ~5.30.2
  svelte-check: ^4.2.1
  tailwindcss: ^4.1.7
  tailwind-merge: ^3.2.0
  typescript: ^5.8.3
  typescript-eslint: ^8.32.0
  vite: ^6.2.5
  vitest: ^3.1.4
  zod: ^3.25.20

strictPeerDependencies: false
updateNotifier: false
sideEffectsCache: false
