packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.39.2
  '@fontsource-variable/material-symbols-outlined': ^5.2.31
  '@fontsource/neuton': ^5.2.7
  '@fontsource/titillium-web': ^5.2.8
  '@sveltejs/adapter-auto': ^7.0.0
  '@sveltejs/kit': ^2.49.5
  '@sveltejs/vite-plugin-svelte': ^6.2.4
  '@tailwindcss/vite': ^4.1.18
  '@trpc/client': ^10.45.4
  '@trpc/server': ^11.8.1
  '@types/jsonwebtoken': ^9.0.10
  '@types/node': ^25.0.9
  '@types/turndown': ^5.0.6
  '@typescript-eslint/eslint-plugin': ^8.32.0
  '@typescript-eslint/parser': ^8.32.0
  '@vitest/browser': ^4.0.17
  '@vitest/browser-playwright': ^4.0.17
  '@vitest/coverage-v8': ^4.0.17
  '@vitest/ui': ^4.0.17
  eslint: ^9.39.2
  eslint-plugin-oxlint: ^1.39.0
  esm-env: ^1.2.2
  globals: ^16.5.0
  jsonwebtoken: ^9.0.3
  oxfmt: ^0.24.0
  oxlint: ^1.39.0
  rimraf: ^6.1.2
  svelte: ^5.46.4
  svelte-check: ^4.3.5
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  turndown: ^7.2.2
  typescript: ^5.9.3
  typescript-eslint: ^8.53.0
  vite: ^7.3.1
  vitest: ^4.0.17
  zod: ^3.25.76

onlyBuiltDependencies:
  - esbuild

sideEffectsCache: false

strictPeerDependencies: false

updateNotifier: false
