packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.26.0
  '@fontsource-variable/material-symbols-outlined': ^5.2.10
  '@fontsource/neuton': ^5.2.5
  '@fontsource/titillium-web': ^5.2.5
  '@sveltejs/adapter-auto': ^6.0.0
  '@sveltejs/kit': ^2.20.8
  '@sveltejs/vite-plugin-svelte': ^5.0.3
  '@tailwindcss/vite': ^4.1.6
  '@trpc/client': ^10.45.2
  '@trpc/server': ^10.45.2
  '@types/jsonwebtoken': ^9.0.2
  '@types/node': ^22.15.17
  '@typescript-eslint/eslint-plugin': ^8.32.0
  '@typescript-eslint/parser': ^8.32.0
  '@vitest/coverage-v8': ^3.1.3
  '@vitest/ui': ^3.1.3
  jsonwebtoken: ^9.0.2
  eslint: ^9.26.0
  globals: ^16.1.0
  prettier: ^3.5.3
  rimraf: ^6.0.1
  svelte: ^5.25.3
  svelte-check: ^4.1.7
  tailwindcss: ^4.1.6
  tailwind-merge: ^3.2.0
  typescript: ^5.8.3
  typescript-eslint: ^8.32.0
  unbuild: ^3.5.0
  vite: ^6.2.5
  vitest: ^3.1.3
  zod: ^3.24.4

strictPeerDependencies: false
updateNotifier: false
