packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.28.0
  '@fontsource-variable/material-symbols-outlined': ^5.2.12
  '@fontsource/neuton': ^5.2.6
  '@fontsource/titillium-web': ^5.2.6
  '@sveltejs/adapter-auto': ^6.0.1
  '@sveltejs/kit': ^2.21.2
  '@sveltejs/vite-plugin-svelte': ^5.1.0
  '@tailwindcss/vite': ^4.1.8
  '@trpc/client': ^10.45.2
  '@trpc/server': ^10.45.2
  '@types/jsonwebtoken': ^9.0.2
  '@types/node': ^22.15.30
  '@types/turndown': ^5.0.5
  '@typescript-eslint/eslint-plugin': ^8.32.0
  '@typescript-eslint/parser': ^8.32.0
  '@vitest/coverage-v8': ^3.2.2
  '@vitest/ui': ^3.2.2
  jsonwebtoken: ^9.0.2
  eslint: ^9.28.0
  esm-env: ^1.2.2
  globals: ^16.2.0
  prettier: ^3.5.3
  rimraf: ^6.0.1
  svelte: ^5.33.18
  svelte-check: ^4.2.1
  tailwindcss: ^4.1.8
  tailwind-merge: ^3.2.0
  turndown: ^7.2.0
  typescript: ^5.8.3
  typescript-eslint: ^8.34.0
  vite: ^6.2.5
  vitest: ^3.2.2
  zod: ^3.25.56

strictPeerDependencies: false
updateNotifier: false
sideEffectsCache: false
