packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.39.2
  '@fontsource-variable/material-symbols-outlined': ^5.2.30
  '@fontsource/neuton': ^5.2.7
  '@fontsource/titillium-web': ^5.2.8
  '@sveltejs/adapter-auto': ^7.0.0
  '@sveltejs/kit': ^2.49.2
  '@sveltejs/vite-plugin-svelte': ^6.02.1
  '@tailwindcss/vite': ^4.1.18
  '@trpc/client': ^10.45.2
  '@trpc/server': ^10.45.3
  '@types/jsonwebtoken': ^9.0.10
  '@types/node': ^25.0.3
  '@types/turndown': ^5.0.6
  '@typescript-eslint/eslint-plugin': ^8.32.0
  '@typescript-eslint/parser': ^8.32.0
  '@vitest/browser': ^4.0.0
  '@vitest/browser-playwright': ^4.0.0
  '@vitest/coverage-v8': ^4.0.0
  '@vitest/ui': ^4.0.0
  jsonwebtoken: ^9.0.3
  eslint: ^9.39.2
  esm-env: ^1.2.2
  globals: ^16.5.0
  prettier: ^3.7.4
  rimraf: ^6.1.2
  svelte: ^5.46.1
  svelte-check: ^4.3.5
  tailwindcss: ^4.1.18
  tailwind-merge: ^3.4.0
  turndown: ^7.2.2
  typescript: ^5.9.3
  typescript-eslint: ^8.35.01
  vite: ^7.3.0
  vitest: ^4.0.0
  zod: ^3.25.75

strictPeerDependencies: false
updateNotifier: false
sideEffectsCache: false
onlyBuiltDependencies:
  - esbuild
