packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.30.1
  '@fontsource-variable/material-symbols-outlined': ^5.2.16
  '@fontsource/neuton': ^5.2.6
  '@fontsource/titillium-web': ^5.2.6
  '@sveltejs/adapter-auto': ^6.0.1
  '@sveltejs/kit': ^2.22.2
  '@sveltejs/vite-plugin-svelte': ^5.1.0
  '@tailwindcss/vite': ^4.1.11
  '@trpc/client': ^10.45.2
  '@trpc/server': ^11.4.4
  '@types/jsonwebtoken': ^9.0.10
  '@types/node': ^24.0.10
  '@types/turndown': ^5.0.5
  '@typescript-eslint/eslint-plugin': ^8.32.0
  '@typescript-eslint/parser': ^8.32.0
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  jsonwebtoken: ^9.0.2
  eslint: ^9.30.1
  esm-env: ^1.2.2
  globals: ^16.3.0
  prettier: ^3.6.2
  rimraf: ^6.0.1
  svelte: ^5.35.2
  svelte-check: ^4.2.2
  tailwindcss: ^4.1.11
  tailwind-merge: ^3.3.1
  turndown: ^7.2.0
  typescript: ^5.8.3
  typescript-eslint: ^8.35.01
  vite: ^6.3.5
  vitest: ^3.2.4
  zod: ^3.25.75

strictPeerDependencies: false
updateNotifier: false
sideEffectsCache: false
