-- region Comments
create table public.comment
(
    id                bigint                                 not null,
    content           text                                   not null,
    updated_at        timestamp with time zone,
    created_by        bigint,
    created_at        timestamp with time zone default now() not null,
    parent_comment_id bigint
);
alter table public.comment
    owner to postgres;
comment on table public.comment is 'A comment on a book, a creator, a series, a publisher, or a collection.';
alter table public.comment
    alter column id add generated by default as identity (
        sequence name public.comment_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.comment to anon;
grant all on table public.comment to authenticated;
grant all on table public.comment to service_role;
grant all on sequence public.comment_id_seq to anon;
grant all on sequence public.comment_id_seq to authenticated;
grant all on sequence public.comment_id_seq to service_role;

alter table public.comment
    enable row level security;

alter table only public.comment
    add constraint comment_pkey primary key (id);

alter table only public.comment
    add constraint comment_created_by_fkey foreign key (created_by) references authentication."user" (id)
        on update cascade on delete cascade;

-- Self-referencing foreign key for threaded comments (cascade deletes replies when parent deleted)
alter table only public.comment
    add constraint comment_parent_comment_id_fkey foreign key (parent_comment_id) references public.comment (id)
        on update cascade on delete cascade;

-- Indexes for efficient reply lookups and ordering
create index idx_comment_parent_comment_id on public.comment (parent_comment_id);
create index idx_comment_created_at on public.comment (created_at);
-- endregion

-- region Comment Reactions
create table public.comment_reaction
(
    comment_id bigint                                 not null,
    user_id    bigint                                 not null,
    emoji      text                                   not null,
    created_at timestamp with time zone default now() not null
);
alter table public.comment_reaction
    owner to postgres;
comment on table public.comment_reaction is 'A single emoji reaction of a user to a comment.';

grant all on table public.comment_reaction to anon;
grant all on table public.comment_reaction to authenticated;
grant all on table public.comment_reaction to service_role;

alter table public.comment_reaction
    enable row level security;

alter table only public.comment_reaction
    add constraint comment_reaction_pkey primary key (comment_id, user_id);

alter table only public.comment_reaction
    add constraint comment_reaction_comment_id_fkey foreign key (comment_id) references public.comment (id)
        on update cascade on delete cascade;
alter table only public.comment_reaction
    add constraint comment_reaction_user_id_fkey foreign key (user_id) references authentication."user" (id)
        on update cascade on delete cascade;
-- endregion

alter table only public.work_comment
    add constraint work_comment_comment_id_fkey foreign key (comment_id) references public.comment (id)
        on update cascade on delete cascade;
alter table only public.collection_comment
    add constraint collection_comment_comment_id_fkey foreign key (comment_id) references public.comment (id)
        on update cascade on delete cascade;

-- region Comment Moderation
-- Hidden/moderated comments (columns on comment table)
alter table public.comment add column hidden_at timestamp with time zone;
alter table public.comment add column hidden_by bigint;
alter table public.comment add column hidden_reason text;

alter table only public.comment
    add constraint comment_hidden_by_fkey foreign key (hidden_by) references authentication."user" (id)
        on update cascade on delete set null;

-- Comment reports table
create table public.comment_report
(
    id          bigint                                 not null,
    comment_id  bigint                                 not null,
    reported_by bigint                                 not null,
    reason      text                                   not null,
    created_at  timestamp with time zone default now() not null,
    resolved_at timestamp with time zone,
    resolved_by bigint,
    resolution  text -- 'dismissed', 'hidden', 'deleted'
);
alter table public.comment_report
    owner to postgres;
comment on table public.comment_report is 'Reports submitted by users for inappropriate comments.';
alter table public.comment_report
    alter column id add generated by default as identity (
        sequence name public.comment_report_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.comment_report to anon;
grant all on table public.comment_report to authenticated;
grant all on table public.comment_report to service_role;
grant all on sequence public.comment_report_id_seq to anon;
grant all on sequence public.comment_report_id_seq to authenticated;
grant all on sequence public.comment_report_id_seq to service_role;

alter table public.comment_report
    enable row level security;

alter table only public.comment_report
    add constraint comment_report_pkey primary key (id);

alter table only public.comment_report
    add constraint comment_report_comment_id_fkey foreign key (comment_id) references public.comment (id)
        on update cascade on delete cascade;
alter table only public.comment_report
    add constraint comment_report_reported_by_fkey foreign key (reported_by) references authentication."user" (id)
        on update cascade on delete cascade;
alter table only public.comment_report
    add constraint comment_report_resolved_by_fkey foreign key (resolved_by) references authentication."user" (id)
        on update cascade on delete set null;
alter table only public.comment_report
    add constraint comment_report_unique_per_user unique (comment_id, reported_by);

create index idx_comment_report_unresolved on public.comment_report (resolved_at) where resolved_at is null;
create index idx_comment_report_comment on public.comment_report (comment_id);
-- endregion

-- region User Blocks
create table public.user_block
(
    blocker_id bigint                                 not null,
    blocked_id bigint                                 not null,
    created_at timestamp with time zone default now() not null
);
alter table public.user_block
    owner to postgres;
comment on table public.user_block is 'Users blocked by other users. Comments from blocked users are hidden.';

grant all on table public.user_block to anon;
grant all on table public.user_block to authenticated;
grant all on table public.user_block to service_role;

alter table public.user_block
    enable row level security;

alter table only public.user_block
    add constraint user_block_pkey primary key (blocker_id, blocked_id);

alter table only public.user_block
    add constraint user_block_blocker_id_fkey foreign key (blocker_id) references authentication."user" (id)
        on update cascade on delete cascade;
alter table only public.user_block
    add constraint user_block_blocked_id_fkey foreign key (blocked_id) references authentication."user" (id)
        on update cascade on delete cascade;

create index idx_user_block_blocker on public.user_block (blocker_id);
-- endregion

-- region Moderation Log
-- Tracks all moderation actions for accountability
create table public.moderation_log
(
    id           bigint                                 not null,
    action_type  text                                   not null, -- 'resolve_report', 'reopen_report', 'hide_comment', 'unhide_comment', 'change_resolution'
    target_type  text                                   not null, -- 'report', 'comment'
    target_id    bigint                                 not null,
    performed_by bigint                                 not null,
    details      jsonb,                                           -- { previous_resolution, new_resolution, reason, comment_content, etc. }
    created_at   timestamp with time zone default now() not null
);
alter table public.moderation_log
    owner to postgres;
comment on table public.moderation_log is 'Audit log of all moderation actions for accountability.';
alter table public.moderation_log
    alter column id add generated by default as identity (
        sequence name public.moderation_log_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.moderation_log to anon;
grant all on table public.moderation_log to authenticated;
grant all on table public.moderation_log to service_role;
grant all on sequence public.moderation_log_id_seq to anon;
grant all on sequence public.moderation_log_id_seq to authenticated;
grant all on sequence public.moderation_log_id_seq to service_role;

alter table public.moderation_log
    enable row level security;

alter table only public.moderation_log
    add constraint moderation_log_pkey primary key (id);

alter table only public.moderation_log
    add constraint moderation_log_performed_by_fkey foreign key (performed_by) references authentication."user" (id)
        on update cascade on delete cascade;

create index idx_moderation_log_created_at on public.moderation_log (created_at desc);
create index idx_moderation_log_performed_by on public.moderation_log (performed_by);
create index idx_moderation_log_target on public.moderation_log (target_type, target_id);
-- endregion
