-- region Images
create table public.image
(
    id                bigint                                       not null,
    storage_reference text                                         not null,
    filename          text                                         not null,
    description       text,
    media_type        text                                         not null,
    width             smallint                                     not null,
    height            smallint                                     not null,
    size              integer                                      not null,
    metadata          jsonb                    default '{}'::jsonb not null,
    updated_by        bigint,
    updated_at        timestamp with time zone,
    created_by        bigint,
    created_at        timestamp with time zone default now()       not null,
    checksum          bytea                                        not null,
    blurhash          text                                         not null,
    constraint image_metadata_check check ((jsonb_typeof(metadata) = 'object'::text)),
    constraint image_storage_reference_check check (storage_reference ~ '^s3://.+/.+'::text)
);
alter table public.image
    owner to postgres;
comment on table public.image is 'Metadata records for images linked to other entities.';
comment on column public.image.storage_reference is 'Address of the file in a physical storage location as an s3:// URI.';
comment on column public.image.filename is 'Name, or key, of the file as persisted to the storage bucket.';
comment on column public.image.description is 'A human-readable description of the image intended for visually impaired users (used as alternative text).';
comment on column public.image.media_type is 'A media type string describing the type of image file (e.g. "image/png" for a PNG file).';
comment on column public.image.width is 'Width of the image, in pixels.';
comment on column public.image.height is 'Height of the image, in pixels.';
comment on column public.image.size is 'Size of the file, in bytes.';
comment on column public.image.metadata is 'JSON object containing image file metadata.';
comment on column public.image.checksum is 'An SHA1 hash of the file, used for ETag headers and sanity checks.';
comment on column public.image.blurhash is 'A blurhash representation of the image; see https://blurha.sh/. Blurhashes are simple string representations of an image that can be used to render a blurred approximation of the original image.';
comment on constraint image_metadata_check on public.image is 'Check that metadata is a JSON object';
comment on constraint image_storage_reference_check on public.image is 'Check for valid s3 URIs';
alter table public.image
    alter column id add generated by default as identity ( sequence name public.image_id_seq start with 1 increment by 1 no minvalue no maxvalue cache 1 );

grant all on table public.image to anon;
grant all on table public.image to authenticated;
grant all on table public.image to service_role;
grant all on sequence public.image_id_seq to anon;
grant all on sequence public.image_id_seq to authenticated;
grant all on sequence public.image_id_seq to service_role;

alter table public.image
    enable row level security;

alter table only public.image
    add constraint image_checksum_key unique (checksum);
alter table only public.image
    add constraint image_storage_reference_key unique (storage_reference);
alter table only public.image
    add constraint image_pkey primary key (id);

alter table only public.image
    add constraint image_created_by_fkey foreign key (created_by) references authentication."user" (id) on update cascade on delete set null;
alter table only public.image
    add constraint image_updated_by_fkey foreign key (updated_by) references authentication."user" (id) on update cascade on delete set null;
-- endregion

-- region Image Creators
create table public.image_creator
(
    image_id   bigint               not null,
    creator_id bigint               not null,
    essential  boolean default true not null
);
alter table public.image_creator
    owner to postgres;
comment on table public.image_creator is 'Junction table for contributions to book edition images by creators.';
alter table public.image_creator
    alter column image_id add generated by default as identity ( sequence name public.image_creator_image_id_seq start with 1 increment by 1 no minvalue no maxvalue cache 1 );

grant all on table public.image_creator to anon;
grant all on table public.image_creator to authenticated;
grant all on table public.image_creator to service_role;
grant all on sequence public.image_creator_image_id_seq to anon;
grant all on sequence public.image_creator_image_id_seq to authenticated;
grant all on sequence public.image_creator_image_id_seq to service_role;

alter table public.image_creator
    enable row level security;
alter table only public.image_creator
    add constraint image_creator_pkey primary key (image_id, creator_id);
alter table only public.image_creator
    add constraint image_creator_image_id_fkey foreign key (image_id) references public.image (id) on update cascade on delete cascade;
-- endregion
