create table public.edition
(
    id                bigint                                 not null,
    work_id           bigint,
    format            text,
    title             text                                   not null,
    binding           text,
    synopsis          text,
    excerpt           text,
    pages             smallint,
    isbn_10           extensions.isbn,
    isbn_13           extensions.isbn13,
    asin              char(10),
    openlibrary_id    text,
    publisher_id      bigint,
    published_at      date,
    updated_by        bigint,
    updated_at        timestamp with time zone,
    created_at        timestamp with time zone default now() not null,
    language          bpchar,
    sorting_key       text,
    cover_image_id    bigint,
    legal_information text
);

alter table public.edition
    owner to postgres;
comment on table public.edition is 'An edition of a work';
comment on column public.edition.title is 'Title of this edition of the work.';
comment on column public.edition.binding is 'Type of binding of this edition of the work (e.g. "hardcover").';
comment on column public.edition.synopsis is 'Synopsis of this edition of the work.';
comment on column public.edition.excerpt is 'An excerpt from the content of the work.';
comment on column public.edition.pages is 'Number of pages in this edition of the work.';
comment on column public.edition.isbn_10 is 'Legacy ISBN-10 identifier of this edition of the work.';
comment on column public.edition.isbn_13 is 'Modern ISBN-13 identifier of this edition of the work.';
comment on column public.edition.asin is 'Amazon Standard Identification Number (ASIN) of this edition of the work. This is a 10-character alphanumeric identifier.';
comment on column public.edition.publisher_id is 'Reference to the publisher of this edition of the work.';
comment on column public.edition.published_at is 'Date the edition of the work has been published.';
comment on column public.edition.sorting_key is 'A version of the edition title intended to used for sorting a list of works (e.g. "Prisoner of Azkaban, the").';
comment on column public.edition.legal_information is 'Any legal information associated with this edition of a work, for example on copyright holders or usage permissions.';
alter table public.edition
    alter column id add generated by default as identity ( sequence name public.edition_id_seq start with 1 increment by 1 no minvalue no maxvalue cache 1 );
alter table public.edition
    add constraint edition_asin_key unique (asin);

grant all on table public.edition to anon;
grant all on table public.edition to authenticated;
grant all on table public.edition to service_role;
grant all on sequence public.edition_id_seq to anon;
grant all on sequence public.edition_id_seq to authenticated;
grant all on sequence public.edition_id_seq to service_role;

alter table public.edition
    enable row level security;

alter table only public.edition
    add constraint edition_pkey primary key (id);

alter table only public.edition
    add constraint check_edition_asin check (asin ~ '^[A-Z0-9]{10}$');

alter table only public.edition
    add constraint edition_work_id_fkey foreign key (work_id) references public.work (id) on update cascade on delete cascade;
alter table only public.edition
    add constraint edition_cover_image_id_fkey foreign key (cover_image_id) references public.image (id) on update cascade on delete set null;
alter table only public.edition
    add constraint edition_updated_by_fkey foreign key (updated_by) references authentication."user" (id) on update cascade on delete set null;
alter table only public.asset
    add constraint asset_edition_id_fkey foreign key (edition_id) references public.edition (id) on update cascade on delete set null;
alter table only public.work
    add constraint work_main_edition_id_fkey foreign key (main_edition_id) references public.edition (id) on update cascade on delete set null;
alter table only public.collection_entry
    add constraint collection_entry_edition_id_fkey foreign key (edition_id) references public.edition (id) on update cascade on delete set null;
alter table only public.contribution
    add constraint contribution_edition_id_fkey foreign key (edition_id) references public.edition (id) on update cascade on delete cascade;
