-- Notifications table for persistent notification storage
create table public.notification
(
    id          bigint generated by default as identity primary key,
    user_id     bigint                   not null,
    type        text                     not null, -- 'comment_reply', 'comment_reaction', 'comment_mention'
    title       text                     not null,
    message     text,
    link        text,
    read_at     timestamp with time zone,
    created_at  timestamp with time zone default now() not null,
    -- Source reference for deduplication
    source_type text,                               -- 'comment', 'reaction'
    source_id   bigint
);

-- Add foreign key constraint
alter table public.notification
    add constraint notification_user_fk
        foreign key (user_id) references authentication.user (id) on delete cascade;

-- Indexes for efficient queries
create index idx_notification_user_unread
    on public.notification (user_id, read_at)
    where read_at is null;

create index idx_notification_user_created
    on public.notification (user_id, created_at desc);

-- Notification preferences per user
create table public.notification_preference
(
    user_id           bigint  primary key,
    comment_replies   boolean default true not null,
    comment_reactions boolean default true not null,
    comment_mentions  boolean default true not null,
    updated_at        timestamp with time zone default now() not null
);

-- Add foreign key constraint
alter table public.notification_preference
    add constraint notification_preference_user_fk
        foreign key (user_id) references authentication.user (id) on delete cascade;
