create table public.asset
(
    id                bigint                                       not null,
    created_at        timestamp with time zone default now()       not null,
    updated_at        timestamp with time zone,
    storage_reference text                                         not null,
    edition_id        bigint                                       not null,
    filename          text                                         not null,
    checksum          bytea                                        not null,
    size              integer                                      not null,
    media_type        text                                         not null,
    metadata          jsonb                    default '{}'::jsonb not null,
    updated_by        bigint,
    created_by        bigint,
    constraint asset_metadata_check check ((jsonb_typeof(metadata) = 'object'::text)),
    constraint asset_storage_reference_check check (asset.storage_reference ~ $$^s3://.+/.+$$)
);

comment on column public.asset.storage_reference is 'Address of the file in a physical storage location as an s3:// URL.';
comment on constraint asset_storage_reference_check on public.asset is 'Check for valid s3 URIs';

alter table public.asset
    owner to postgres;
alter table public.asset
    alter column id add generated by default as identity ( sequence name public.asset_id_seq start with 1 increment by 1 no minvalue no maxvalue cache 1 );
alter table only public.asset
    add constraint asset_storage_reference_key unique (storage_reference);
alter table only public.asset
    add constraint asset_checksum_key unique (checksum);

grant all on table public.asset to anon;
grant all on table public.asset to authenticated;
grant all on table public.asset to service_role;
grant all on sequence public.asset_id_seq to anon;
grant all on sequence public.asset_id_seq to authenticated;
grant all on sequence public.asset_id_seq to service_role;

alter table public.asset
    enable row level security;

alter table only public.asset
    add constraint asset_pkey primary key (id);

alter table only public.asset
    add constraint asset_created_by_fkey foreign key (created_by) references authentication."user" (id) on update cascade on delete set null;
alter table only public.asset
    add constraint asset_updated_by_fkey foreign key (updated_by) references authentication."user" (id) on update cascade on delete set null;
