-- region Works
create table public.work
(
    id              bigint                                 not null,
    created_at      timestamp with time zone default now() not null,
    updated_at      timestamp with time zone,
    updated_by      bigint,
    main_edition_id bigint,
    created_by      bigint
);
alter table public.work
    owner to postgres;
comment on table public.work is 'Container for a set of editions of the same work. Represented by a single edition.';
comment on column public.work.main_edition_id is 'The main, or preferred, edition of a work. Represents the work in listings and collections.';
alter table public.work
    alter column id add generated by default as identity (
        sequence name public.work_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.work to anon;
grant all on table public.work to authenticated;
grant all on table public.work to service_role;
grant all on sequence public.work_id_seq to anon;
grant all on sequence public.work_id_seq to authenticated;
grant all on sequence public.work_id_seq to service_role;

alter table public.work
    enable row level security;

alter table only public.work
    add constraint work_pkey primary key (id);
-- endregion

-- region Work Comments
create table public.work_comment
(
    work_id    bigint not null,
    comment_id bigint not null
);
alter table public.work_comment
    owner to postgres;
comment on table public.work_comment is 'Junction table for comments on works.';
alter table public.work_comment
    alter column work_id add generated by default as identity (
        sequence name public.work_comment_work_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.work_comment to anon;
grant all on table public.work_comment to authenticated;
grant all on table public.work_comment to service_role;
grant all on sequence public.work_comment_work_id_seq to anon;
grant all on sequence public.work_comment_work_id_seq to authenticated;
grant all on sequence public.work_comment_work_id_seq to service_role;

alter table public.work_comment
    enable row level security;

alter table only public.work_comment
    add constraint work_comment_pkey primary key (work_id, comment_id);

-- endregion

-- region Work Ratings
create table public.work_rating
(
    user_id    bigint                                 not null,
    work_id    bigint                                 not null,
    rating     smallint                               not null,
    created_at timestamp with time zone default now() not null
);
alter table public.work_rating
    owner to postgres;
comment on table public.work_rating is 'Junction table for a user''s rating for a book.';
alter table public.work_rating
    alter column work_id add generated by default as identity (
        sequence name public.work_rating_work_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.work_rating to anon;
grant all on table public.work_rating to authenticated;
grant all on table public.work_rating to service_role;
grant all on sequence public.work_rating_work_id_seq to anon;
grant all on sequence public.work_rating_work_id_seq to authenticated;
grant all on sequence public.work_rating_work_id_seq to service_role;

alter table public.work_rating
    enable row level security;

alter table only public.work_rating
    add constraint work_rating_pkey primary key (user_id, work_id);
-- endregion

-- region Work Tags
create table public.work_tag
(
    work_id bigint not null,
    tag_id  bigint not null
);
alter table public.work_tag
    owner to postgres;
comment on table public.work_tag is 'Junction table for work tags';
alter table public.work_tag
    alter column work_id add generated by default as identity (
        sequence name public.work_tag_work_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.work_tag to anon;
grant all on table public.work_tag to authenticated;
grant all on table public.work_tag to service_role;
grant all on sequence public.work_tag_work_id_seq to anon;
grant all on sequence public.work_tag_work_id_seq to authenticated;
grant all on sequence public.work_tag_work_id_seq to service_role;

alter table public.work_tag
    enable row level security;

alter table only public.work_tag
    add constraint work_tag_pkey primary key (work_id, tag_id);
-- endregion

alter table only public.work
    add constraint work_updated_by_fkey foreign key (updated_by) references authentication."user" (id)
        on update cascade on delete set null;
alter table only public.work
    add constraint work_created_by_fkey foreign key (created_by) references authentication."user" (id)
        on update cascade on delete set null;

alter table only public.work_comment
    add constraint work_comment_work_id_fkey foreign key (work_id) references public.work (id)
        on update cascade on delete cascade;

alter table only public.work_rating
    add constraint work_rating_work_id_fkey foreign key (work_id) references public.work (id)
        on update cascade on delete cascade;
alter table only public.work_rating
    add constraint work_rating_user_id_fkey foreign key (user_id) references authentication."user" (id)
        on update cascade on delete cascade;

alter table only public.work_tag
    add constraint work_tag_work_id_fkey foreign key (work_id) references public.work (id)
        on update cascade on delete cascade;
