-- region Collections
create table public.collection
(
    id              bigint                                         not null,
    name            text                                           not null,
    color           bytea,
    emoji           text,
    description     text,
    age_requirement smallint                 default '0'::smallint not null,
    shared          boolean                  default true          not null,
    updated_by      bigint,
    updated_at      timestamp with time zone,
    created_by      bigint,
    created_at      timestamp with time zone default now()         not null,
    constraint collection_age_requirement_check check ((age_requirement >= 0)),
    constraint collection_name_check check ((length(name) < 151))
);
alter table public.collection
    owner to postgres;
comment on table public.collection is 'A collection of works created by a user';
comment on column public.collection.name is 'Mandatory collection name. Must be less than 150 characters.';
comment on column public.collection.color is 'Optional hex color to tint this collection. Does not allow transparency (which will be applied by the application).';
comment on column public.collection.emoji is 'Optional emoji to represent this collection, acting as an icon.';
comment on column public.collection.description is 'Optional long-form description of this collection formatted as Markdown.';
comment on column public.collection.age_requirement is 'Minimum age in years users must reach to access this collection. This obviously will only work if a birthdate has been set for a user.';
comment on column public.collection.shared is 'Shared collections are accessible by all users; personal collections (shared is false) are only visible to the user who created them.';
alter table public.collection
    alter column id add generated by default as identity (
        sequence name public.collection_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.collection to anon;
grant all on table public.collection to authenticated;
grant all on table public.collection to service_role;
grant all on sequence public.collection_id_seq to anon;
grant all on sequence public.collection_id_seq to authenticated;
grant all on sequence public.collection_id_seq to service_role;

alter table public.collection
    enable row level security;

alter table only public.collection
    add constraint collection_pkey primary key (id);

alter table only public.collection
    add constraint collection_created_by_fkey foreign key (created_by) references authentication."user" (id)
        on update cascade on delete set null;
alter table only public.collection
    add constraint collection_updated_by_fkey foreign key (updated_by) references authentication."user" (id)
        on update cascade on delete set null;
-- endregion

-- region Collection Comments
create table public.collection_comment
(
    collection_id bigint not null,
    comment_id    bigint not null
);
alter table public.collection_comment
    owner to postgres;
comment on table public.collection_comment is 'Junction table for comments on collections.';
alter table public.collection_comment
    alter column collection_id add generated by default as identity (
        sequence name public.collection_comment_collection_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.collection_comment to anon;
grant all on table public.collection_comment to authenticated;
grant all on table public.collection_comment to service_role;
grant all on sequence public.collection_comment_collection_id_seq to anon;
grant all on sequence public.collection_comment_collection_id_seq to authenticated;
grant all on sequence public.collection_comment_collection_id_seq to service_role;

alter table public.collection_comment
    enable row level security;

alter table only public.collection_comment
    add constraint collection_comment_pkey primary key (collection_id, comment_id);

alter table only public.collection_comment
    add constraint collection_comment_collection_id_fkey foreign key (collection_id) references public.collection (id)
        on update cascade on delete cascade;
-- endregion

-- region Collection Entries
create table public.collection_entry
(
    collection_id bigint                                 not null,
    work_id       bigint                                 not null,
    edition_id    bigint                                 not null,
    "position"    integer                                not null,
    updated_by    bigint,
    updated_at    timestamp with time zone,
    created_by    bigint,
    created_at    timestamp with time zone default now() not null
);
alter table public.collection_entry
    owner to postgres;
comment on table public.collection_entry is 'Junction table for works in a collection.';
comment on column public.collection_entry.work_id is 'Reference to the work this entry refers to. Unless a specific edition is referenced in `edition_id`, the main edition will be used.';
comment on column public.collection_entry.edition_id is 'Optional specific edition of a work to add. This is useful to create a collection of audio books, for example. If not set, the main edition of the work will be used.';
comment on column public.collection_entry."position" is 'Order position of the collection entry. Applies to all users. To change the position, a reordering of all other collection entries is required.';

grant all on table public.collection_entry to anon;
grant all on table public.collection_entry to authenticated;
grant all on table public.collection_entry to service_role;

alter table public.collection_entry
    enable row level security;

alter table only public.collection_entry
    add constraint collection_entry_pkey primary key (collection_id, work_id, edition_id);

alter table only public.collection_entry
    add constraint collection_entry_work_id_fkey foreign key (work_id) references public.work (id)
        on update cascade on delete cascade;
alter table only public.collection_entry
    add constraint collection_entry_collection_id_fkey foreign key (collection_id) references public.collection (id)
        on update cascade on delete cascade;
alter table only public.collection_entry
    add constraint collection_entry_created_by_fkey foreign key (created_by) references authentication."user" (id)
        on update cascade on delete set null;
alter table only public.collection_entry
    add constraint collection_entry_updated_by_fkey foreign key (updated_by) references authentication."user" (id)
        on update cascade on delete set null;
-- endregion

-- region Collection Tags
create table public.collection_tag
(
    collection_id bigint not null,
    tag_id        bigint not null
);
alter table public.collection_tag
    owner to postgres;
comment on table public.collection_tag is 'Junction table for collection tags';
alter table public.collection_tag
    alter column collection_id add generated by default as identity (
        sequence name public.collection_tag_collection_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.collection_tag to anon;
grant all on table public.collection_tag to authenticated;
grant all on table public.collection_tag to service_role;
grant all on sequence public.collection_tag_collection_id_seq to anon;
grant all on sequence public.collection_tag_collection_id_seq to authenticated;
grant all on sequence public.collection_tag_collection_id_seq to service_role;

alter table public.collection_tag
    enable row level security;

alter table only public.collection_tag
    add constraint collection_tag_pkey primary key (collection_id, tag_id);

alter table only public.collection_tag
    add constraint collection_tag_collection_id_fkey foreign key (collection_id) references public.collection (id)
        on update cascade on delete cascade;
-- endregion
