-- region Comments
create table public.comment
(
    id         bigint                                 not null,
    content    text                                   not null,
    updated_at timestamp with time zone,
    created_by bigint,
    created_at timestamp with time zone default now() not null
);
alter table public.comment
    owner to postgres;
comment on table public.comment is 'A comment on a book, a creator, a series, a publisher, or a collection.';
alter table public.comment
    alter column id add generated by default as identity (
        sequence name public.comment_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.comment to anon;
grant all on table public.comment to authenticated;
grant all on table public.comment to service_role;
grant all on sequence public.comment_id_seq to anon;
grant all on sequence public.comment_id_seq to authenticated;
grant all on sequence public.comment_id_seq to service_role;

alter table public.comment
    enable row level security;

alter table only public.comment
    add constraint comment_pkey primary key (id);

alter table only public.comment
    add constraint comment_created_by_fkey foreign key (created_by) references authentication."user" (id)
        on update cascade on delete cascade;
-- endregion

-- region Comment Reactions
create table public.comment_reaction
(
    comment_id bigint                                 not null,
    user_id    bigint                                 not null,
    emoji      text                                   not null,
    created_at timestamp with time zone default now() not null
);
alter table public.comment_reaction
    owner to postgres;
comment on table public.comment_reaction is 'A single emoji reaction of a user to a comment.';

grant all on table public.comment_reaction to anon;
grant all on table public.comment_reaction to authenticated;
grant all on table public.comment_reaction to service_role;

alter table public.comment_reaction
    enable row level security;

alter table only public.comment_reaction
    add constraint comment_reaction_pkey primary key (comment_id, user_id);

alter table only public.comment_reaction
    add constraint comment_reaction_comment_id_fkey foreign key (comment_id) references public.comment (id)
        on update cascade on delete cascade;
alter table only public.comment_reaction
    add constraint comment_reaction_user_id_fkey foreign key (user_id) references authentication."user" (id)
        on update cascade on delete cascade;
-- endregion

alter table only public.work_comment
    add constraint work_comment_comment_id_fkey foreign key (comment_id) references public.comment (id)
        on update cascade on delete cascade;
alter table only public.collection_comment
    add constraint collection_comment_comment_id_fkey foreign key (comment_id) references public.comment (id)
        on update cascade on delete cascade;
