-- region Creators
create table public.creator
(
    id             bigint                                 not null,
    name           text                                   not null,
    sorting_key    text,
    description    text,
    url            text,
    wikipedia_url  text,
    goodreads_id   text,
    amazon_id      text,
    patreon_id     text,
    openlibrary_id text,
    image_id       bigint,
    birth_date     date,
    death_date     date,
    updated_by     bigint,
    created_at     timestamp with time zone default now() not null,
    updated_at     timestamp with time zone
);
alter table public.creator
    owner to postgres;
comment on table public.creator is 'A creator contributes something to a specific edition of a book; that''s the author, obviously, but also illustrators or translators, for example, or narrators for audio books.';
comment on column public.creator.name is 'Full name of the creator.';
comment on column public.creator.description is 'Description, or biography, of a creator (e.g. an author). Free-text, providing more information on a given creator. Should be provided as Markdown.';
comment on column public.creator.url is 'Link to the website operated by, or another location on the internet representative of, the creator.';
alter table public.creator
    alter column id add generated by default as identity ( sequence name public.creator_id_seq start with 1 increment by 1 no minvalue no maxvalue cache 1 );

grant all on table public.creator to anon;
grant all on table public.creator to authenticated;
grant all on table public.creator to service_role;
grant all on sequence public.creator_id_seq to anon;
grant all on sequence public.creator_id_seq to authenticated;
grant all on sequence public.creator_id_seq to service_role;

alter table public.creator
    enable row level security;
alter table only public.creator
    add constraint creator_pkey primary key (id);
alter table only public.creator
    add constraint creator_updated_by_fkey foreign key (updated_by) references authentication."user" (id) on update cascade on delete set null;
alter table only public.creator
    add constraint creator_image_id_fkey foreign key (image_id) references public.image (id) on update cascade on delete set null;
-- endregion

-- region Creator Comments
create table public.creator_comment
(
    creator_id bigint not null,
    comment_id bigint not null
);
alter table public.creator_comment
    owner to postgres;
comment on table public.creator_comment is 'Junction table for comments on creators.';
alter table public.creator_comment
    alter column creator_id add generated by default as identity ( sequence name public.creator_comment_creator_id_seq start with 1 increment by 1 no minvalue no maxvalue cache 1 );

grant all on table public.creator_comment to anon;
grant all on table public.creator_comment to authenticated;
grant all on table public.creator_comment to service_role;
grant all on sequence public.creator_comment_creator_id_seq to anon;
grant all on sequence public.creator_comment_creator_id_seq to authenticated;
grant all on sequence public.creator_comment_creator_id_seq to service_role;

alter table public.creator_comment
    enable row level security;

alter table only public.creator_comment
    add constraint creator_comment_pkey primary key (creator_id, comment_id);

alter table only public.creator_comment
    add constraint creator_comment_comment_id_fkey foreign key (comment_id) references public.comment (id) on update cascade on delete cascade;
alter table only public.creator_comment
    add constraint creator_comment_creator_id_fkey foreign key (creator_id) references public.creator (id) on update cascade on delete cascade;
-- endregion

alter table only public.contribution
    add constraint contribution_creator_id_fkey foreign key (creator_id) references public.creator (id) on update cascade on delete cascade;
alter table only public.image_creator
    add constraint image_creator_creator_id_fkey foreign key (creator_id) references public.creator (id) on update cascade on delete cascade;
