create table public.edition
(
    id                bigint                                 not null,
    book_id           bigint,
    format            text,
    title             text                                   not null,
    binding           text,
    synopsis          text,
    excerpt           text,
    pages             smallint,
    isbn_10           extensions.isbn,
    isbn_13           extensions.isbn13,
    publisher_id      bigint,
    published_at      date,
    updated_by        bigint,
    updated_at        timestamp with time zone,
    created_at        timestamp with time zone default now() not null,
    language          bpchar,
    sorting_key       text,
    cover_id          bigint,
    legal_information text
);
alter table public.edition
    owner to postgres;
comment on table public.edition is 'An edition of a book';
comment on column public.edition.title is 'Title of this edition of the book.';
comment on column public.edition.binding is 'Type of binding of this edition of the book (e.g. "hardcover").';
comment on column public.edition.synopsis is 'Synopsis of this edition of the book.';
comment on column public.edition.excerpt is 'An excerpt from the content of the book.';
comment on column public.edition.pages is 'Number of pages in this edition of the book.';
comment on column public.edition.isbn_10 is 'Legacy ISBN-10 identifier of this edition of the book.';
comment on column public.edition.isbn_13 is 'Modern ISBN-13 identifier of this edition of the book.';
comment on column public.edition.publisher_id is 'Reference to the publisher of this edition of the book.';
comment on column public.edition.published_at is 'Date the edition of the book has been published.';
comment on column public.edition.sorting_key is 'A version of the book title intended to used for sorting a list of books (e.g. "Prisoner of Azkaban, the").';
comment on column public.edition.legal_information is 'Any legal information associated with this edition of a book, for example on copyright holders or usage permissions.';
alter table public.edition
    alter column id add generated by default as identity (
        sequence name public.edition_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.edition to anon;
grant all on table public.edition to authenticated;
grant all on table public.edition to service_role;
grant all on sequence public.edition_id_seq to anon;
grant all on sequence public.edition_id_seq to authenticated;
grant all on sequence public.edition_id_seq to service_role;

alter table public.edition
    enable row level security;

alter table only public.edition
    add constraint edition_pkey primary key (id);

alter table only public.edition
    add constraint edition_book_id_fkey foreign key (book_id) references public.book (id)
        on update cascade on delete cascade;
alter table only public.edition
    add constraint edition_cover_id_fkey foreign key (cover_id) references public.cover (id)
        on update cascade on delete set null;
alter table only public.edition
    add constraint edition_updated_by_fkey foreign key (updated_by) references authentication."user" (id)
        on update cascade on delete set null;
alter table only public.asset
    add constraint asset_edition_id_fkey foreign key (edition_id) references public.edition (id)
        on update cascade on delete set null;
alter table only public.book
    add constraint book_main_edition_id_fkey foreign key (main_edition_id) references public.edition (id)
        on update cascade on delete set null;
alter table only public.collection_entry
    add constraint collection_entry_edition_id_fkey foreign key (edition_id) references public.edition (id)
        on update cascade on delete set null;
alter table only public.contribution
    add constraint contribution_edition_id_fkey foreign key (edition_id) references public.edition (id)
        on update cascade on delete cascade;
