-- region Series
create table public.series
(
    id         bigint                                 not null,
    name       text,
    updated_by bigint,
    updated_at timestamp with time zone,
    created_at timestamp with time zone default now() not null,
    language   bpchar
);
alter table public.series
    owner to postgres;
comment on column public.series.name is 'Name of the series of books.';
alter table public.series
    alter column id add generated by default as identity (
        sequence name public.series_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.series to anon;
grant all on table public.series to authenticated;
grant all on table public.series to service_role;
grant all on sequence public.series_id_seq to anon;
grant all on sequence public.series_id_seq to authenticated;
grant all on sequence public.series_id_seq to service_role;

alter table public.series
    enable row level security;

alter table only public.series
    add constraint series_pkey primary key (id);

alter table only public.series
    add constraint series_language_fkey foreign key (language) references public.language (iso_639_3)
        on update cascade on delete set null;
alter table only public.series
    add constraint series_updated_by_fkey foreign key (updated_by) references authentication."user" (id)
        on update cascade on delete set null;
-- endregion

-- region Series Comments
create table public.series_comment
(
    series_id  bigint not null,
    comment_id bigint
);
alter table public.series_comment
    owner to postgres;
comment on table public.series_comment is 'Junction table for comments on series.';
alter table public.series_comment
    alter column series_id add generated by default as identity (
        sequence name public.series_comment_series_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.series_comment to anon;
grant all on table public.series_comment to authenticated;
grant all on table public.series_comment to service_role;
grant all on sequence public.series_comment_series_id_seq to anon;
grant all on sequence public.series_comment_series_id_seq to authenticated;
grant all on sequence public.series_comment_series_id_seq to service_role;

alter table public.series_comment
    enable row level security;

alter table only public.series_comment
    add constraint series_comment_pkey primary key (series_id);

alter table only public.series_comment
    add constraint series_comment_comment_id_fkey foreign key (comment_id) references public.comment (id)
        on update cascade on delete cascade;
alter table only public.series_comment
    add constraint series_comment_series_id_fkey foreign key (series_id) references public.series (id)
        on update cascade on delete cascade;
-- endregion

-- region Series Entries
create table public.series_entry
(
    book_id    bigint not null,
    series_id  bigint not null,
    "position" smallint
);
alter table public.series_entry
    owner to postgres;
comment on column public.series_entry."position" is 'Position of the given boko in the series.';
alter table public.series_entry
    alter column book_id add generated by default as identity (
        sequence name public.series_entry_book_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.series_entry to anon;
grant all on table public.series_entry to authenticated;
grant all on table public.series_entry to service_role;
grant all on sequence public.series_entry_book_id_seq to anon;
grant all on sequence public.series_entry_book_id_seq to authenticated;
grant all on sequence public.series_entry_book_id_seq to service_role;

alter table public.series_entry
    enable row level security;

alter table only public.series_entry
    add constraint series_entry_pkey primary key (book_id, series_id);

alter table only public.series_entry
    add constraint series_entry_book_id_fkey foreign key (book_id) references public.book (id)
        on update cascade on delete cascade;
alter table only public.series_entry
    add constraint series_entry_series_id_fkey foreign key (series_id) references public.series (id)
        on update cascade on delete cascade;
-- endregion

-- region Series Tags
create table public.series_tag
(
    series_id bigint not null,
    tag_id    bigint not null
);
alter table public.series_tag
    owner to postgres;
comment on table public.series_tag is 'Junction table for series tags';
alter table public.series_tag
    alter column series_id add generated by default as identity (
        sequence name public.series_tag_series_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.series_tag to anon;
grant all on table public.series_tag to authenticated;
grant all on table public.series_tag to service_role;
grant all on sequence public.series_tag_series_id_seq to anon;
grant all on sequence public.series_tag_series_id_seq to authenticated;
grant all on sequence public.series_tag_series_id_seq to service_role;

alter table public.series_tag
    enable row level security;

alter table only public.series_tag
    add constraint series_tag_pkey primary key (series_id, tag_id);

alter table only public.series_tag
    add constraint series_tag_series_id_fkey foreign key (series_id) references public.series (id)
        on update cascade on delete cascade;
-- endregion
