create table public.tag
(
    id         bigint                                 not null,
    value      text                                   not null,
    color      text,
    emoji      text,
    created_by bigint,
    created_at timestamp with time zone default now() not null
);
alter table public.tag
    owner to postgres;
comment on table public.tag is 'Tags for collections, books, series, and creators';
alter table public.tag
    alter column id add generated by default as identity (
        sequence name public.tag_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.tag to anon;
grant all on table public.tag to authenticated;
grant all on table public.tag to service_role;
grant all on sequence public.tag_id_seq to anon;
grant all on sequence public.tag_id_seq to authenticated;
grant all on sequence public.tag_id_seq to service_role;

alter table public.tag
    enable row level security;

alter table only public.tag
    add constraint tag_pkey primary key (id);

alter table only public.tag
    add constraint tag_created_by_fkey foreign key (created_by) references authentication."user" (id)
        on update cascade on delete set null;

alter table only public.book_tag
    add constraint book_tag_tag_id_fkey foreign key (tag_id) references public.tag (id)
        on update cascade on delete cascade;
alter table only public.collection_tag
    add constraint collection_tag_tag_id_fkey foreign key (tag_id) references public.tag (id)
        on update cascade on delete cascade;
alter table only public.series_tag
    add constraint series_tag_tag_id_fkey foreign key (tag_id) references public.tag (id)
        on update cascade on delete cascade;
