-- region Favorite Collections
create table public.user_collection_favorite
(
    user_id       bigint not null,
    collection_id bigint not null
);
alter table public.user_collection_favorite
    owner to postgres;
comment on table public.user_collection_favorite is 'Junction table for favorite user collections.';
alter table public.user_collection_favorite
    alter column user_id add generated by default as identity (
        sequence name public.user_collection_favorite_user_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.user_collection_favorite to anon;
grant all on table public.user_collection_favorite to authenticated;
grant all on table public.user_collection_favorite to service_role;
grant all on sequence public.user_collection_favorite_user_id_seq to anon;
grant all on sequence public.user_collection_favorite_user_id_seq to authenticated;
grant all on sequence public.user_collection_favorite_user_id_seq to service_role;

alter table public.user_collection_favorite
    enable row level security;

alter table only public.user_collection_favorite
    add constraint user_collection_favorite_pkey primary key (user_id, collection_id);

alter table only public.user_collection_favorite
    add constraint user_collection_favorite_collection_id_fkey foreign key (collection_id) references public.collection (id)
        on update cascade on delete cascade;
alter table only public.user_collection_favorite
    add constraint user_collection_favorite_user_id_fkey foreign key (user_id) references authentication."user" (id)
        on update cascade on delete cascade;
-- endregion

-- region Favorite Creators
create table public.user_creator_favorite
(
    user_id    bigint not null,
    creator_id bigint not null
);
alter table public.user_creator_favorite
    owner to postgres;
comment on table public.user_creator_favorite is 'Junction table for favorite creators.';
alter table public.user_creator_favorite
    alter column user_id add generated by default as identity (
        sequence name public.user_creator_favorite_user_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.user_creator_favorite to anon;
grant all on table public.user_creator_favorite to authenticated;
grant all on table public.user_creator_favorite to service_role;
grant all on sequence public.user_creator_favorite_user_id_seq to anon;
grant all on sequence public.user_creator_favorite_user_id_seq to authenticated;
grant all on sequence public.user_creator_favorite_user_id_seq to service_role;

alter table public.user_creator_favorite
    enable row level security;

alter table only public.user_creator_favorite
    add constraint user_creator_favorite_pkey primary key (user_id, creator_id);

alter table only public.user_creator_favorite
    add constraint user_creator_favorite_creator_id_fkey foreign key (creator_id) references public.creator (id)
        on update cascade on delete cascade;
alter table only public.user_creator_favorite
    add constraint user_creator_favorite_user_id_fkey foreign key (user_id) references authentication."user" (id)
        on update cascade on delete cascade;
-- endregion
