create table public.asset
(
    id         bigint                                       not null,
    created_at timestamp with time zone default now()       not null,
    updated_at timestamp with time zone,
    edition_id bigint                                       not null,
    filename   text                                         not null,
    checksum   bytea                                        not null,
    size       integer                                      not null,
    media_type text                                         not null,
    metadata   jsonb                    default '{}'::jsonb not null,
    updated_by bigint,
    created_by bigint,
    constraint asset_metadata_check check ((jsonb_typeof(metadata) = 'object'::text))
);
alter table public.asset
    owner to postgres;
alter table public.asset
    alter column id add generated by default as identity (
        sequence name public.asset_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.asset to anon;
grant all on table public.asset to authenticated;
grant all on table public.asset to service_role;
grant all on sequence public.asset_id_seq to anon;
grant all on sequence public.asset_id_seq to authenticated;
grant all on sequence public.asset_id_seq to service_role;

alter table public.asset
    enable row level security;

alter table only public.asset
    add constraint asset_pkey primary key (id);

alter table only public.asset
    add constraint asset_created_by_fkey foreign key (created_by) references authentication."user" (id)
        on update cascade on delete set null;
alter table only public.asset
    add constraint asset_updated_by_fkey foreign key (updated_by) references authentication."user" (id)
        on update cascade on delete set null;
