-- region Books
create table public.book
(
    id              bigint                                 not null,
    created_at      timestamp with time zone default now() not null,
    updated_at      timestamp with time zone,
    updated_by      bigint,
    main_edition_id bigint,
    created_by      bigint
);
alter table public.book
    owner to postgres;
comment on table public.book is 'Container for a set of editions of the same book. Represented by a single edition.';
comment on column public.book.main_edition_id is 'The main, or preferred, edition of a book. Represents the book in listings and collections.';
alter table public.book
    alter column id add generated by default as identity (
        sequence name public.book_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.book to anon;
grant all on table public.book to authenticated;
grant all on table public.book to service_role;
grant all on sequence public.book_id_seq to anon;
grant all on sequence public.book_id_seq to authenticated;
grant all on sequence public.book_id_seq to service_role;

alter table public.book
    enable row level security;

alter table only public.book
    add constraint book_pkey primary key (id);
-- endregion

-- region Book Comments
create table public.book_comment
(
    book_id    bigint not null,
    comment_id bigint not null
);
alter table public.book_comment
    owner to postgres;
comment on table public.book_comment is 'Junction table for comments on books.';
alter table public.book_comment
    alter column book_id add generated by default as identity (
        sequence name public.book_comment_book_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.book_comment to anon;
grant all on table public.book_comment to authenticated;
grant all on table public.book_comment to service_role;
grant all on sequence public.book_comment_book_id_seq to anon;
grant all on sequence public.book_comment_book_id_seq to authenticated;
grant all on sequence public.book_comment_book_id_seq to service_role;

alter table public.book_comment
    enable row level security;

alter table only public.book_comment
    add constraint book_comment_pkey primary key (book_id, comment_id);

-- endregion

-- region Book Ratings
create table public.book_rating
(
    user_id    bigint                                 not null,
    book_id    bigint                                 not null,
    rating     smallint                               not null,
    created_at timestamp with time zone default now() not null
);
alter table public.book_rating
    owner to postgres;
comment on table public.book_rating is 'Junction table for a user''s rating for a book.';
alter table public.book_rating
    alter column book_id add generated by default as identity (
        sequence name public.book_rating_book_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.book_rating to anon;
grant all on table public.book_rating to authenticated;
grant all on table public.book_rating to service_role;
grant all on sequence public.book_rating_book_id_seq to anon;
grant all on sequence public.book_rating_book_id_seq to authenticated;
grant all on sequence public.book_rating_book_id_seq to service_role;

alter table public.book_rating
    enable row level security;

alter table only public.book_rating
    add constraint book_rating_pkey primary key (user_id, book_id);
-- endregion

-- region Book Tags
create table public.book_tag
(
    book_id bigint not null,
    tag_id  bigint not null
);
alter table public.book_tag
    owner to postgres;
comment on table public.book_tag is 'Junction table for book tags';
alter table public.book_tag
    alter column book_id add generated by default as identity (
        sequence name public.book_tag_book_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.book_tag to anon;
grant all on table public.book_tag to authenticated;
grant all on table public.book_tag to service_role;
grant all on sequence public.book_tag_book_id_seq to anon;
grant all on sequence public.book_tag_book_id_seq to authenticated;
grant all on sequence public.book_tag_book_id_seq to service_role;

alter table public.book_tag
    enable row level security;

alter table only public.book_tag
    add constraint book_tag_pkey primary key (book_id, tag_id);
-- endregion

alter table only public.book
    add constraint book_updated_by_fkey foreign key (updated_by) references authentication."user" (id)
        on update cascade on delete set null;
alter table only public.book
    add constraint book_created_by_fkey foreign key (created_by) references authentication."user" (id)
        on update cascade on delete set null;

alter table only public.book_comment
    add constraint book_comment_book_id_fkey foreign key (book_id) references public.book (id)
        on update cascade on delete cascade;

alter table only public.book_rating
    add constraint book_rating_book_id_fkey foreign key (book_id) references public.book (id)
        on update cascade on delete cascade;
alter table only public.book_rating
    add constraint book_rating_user_id_fkey foreign key (user_id) references authentication."user" (id)
        on update cascade on delete cascade;

alter table only public.book_tag
    add constraint book_tag_book_id_fkey foreign key (book_id) references public.book (id)
        on update cascade on delete cascade;
