-- region Publishers
create table public.publisher
(
    id            bigint                                 not null,
    name          character varying                      not null,
    sorting_key   character varying                      not null,
    description   text,
    image         character varying,
    url           character varying,
    wikipedia_url character varying,
    updated_by    bigint,
    updated_at    timestamp with time zone,
    created_at    timestamp with time zone default now() not null
);
alter table public.publisher
    owner to postgres;
comment on table public.publisher is 'A company publishing books.';
alter table public.publisher
    alter column id add generated by default as identity (
        sequence name public.publisher_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.publisher to anon;
grant all on table public.publisher to authenticated;
grant all on table public.publisher to service_role;
grant all on sequence public.publisher_id_seq to anon;
grant all on sequence public.publisher_id_seq to authenticated;
grant all on sequence public.publisher_id_seq to service_role;

alter table public.publisher
    enable row level security;

alter table only public.publisher
    add constraint publisher_pkey primary key (id);

alter table only public.publisher
    add constraint publisher_updated_by_fkey foreign key (updated_by) references authentication."user" (id)
        on update cascade on delete set null;
-- endregion

-- region Publisher Comments
create table public.publisher_comment
(
    publisher_id bigint not null,
    comment_id   bigint not null
);
alter table public.publisher_comment
    owner to postgres;
comment on table public.publisher_comment is 'Junction table for comments on publishers.';
alter table public.publisher_comment
    alter column publisher_id add generated by default as identity (
        sequence name public.publisher_comment_publisher_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.publisher_comment to anon;
grant all on table public.publisher_comment to authenticated;
grant all on table public.publisher_comment to service_role;
grant all on sequence public.publisher_comment_publisher_id_seq to anon;
grant all on sequence public.publisher_comment_publisher_id_seq to authenticated;
grant all on sequence public.publisher_comment_publisher_id_seq to service_role;

alter table public.publisher_comment
    enable row level security;

alter table only public.publisher_comment
    add constraint publisher_comment_pkey primary key (publisher_id, comment_id);

alter table only public.publisher_comment
    add constraint publisher_comment_comment_id_fkey foreign key (comment_id) references public.comment (id)
        on update cascade on delete cascade;
alter table only public.publisher_comment
    add constraint publisher_comment_publisher_id_fkey foreign key (publisher_id) references public.publisher (id)
        on update cascade on delete cascade;
-- endregion

alter table only public.edition
    add constraint edition_publisher_id_fkey foreign key (publisher_id) references public.publisher (id)
        on update cascade on delete set null;
