create table public.review
(
    id               bigint                                 not null,
    edition_id       bigint                                 not null,
    content          text                                   not null,
    reviewer_id      bigint,
    publication_name text,
    published_at     date,
    updated_by       bigint,
    updated_at       timestamp with time zone,
    created_at       timestamp with time zone default now() not null,
    url              text,
    excerpt          text,
    constraint review_excerpt_check check ((length(excerpt) < 201))
);
alter table public.review
    owner to postgres;
comment on table public.review is 'A published book review.';
comment on column public.review.edition_id is 'Reference to the edition of a book this review refers to.';
comment on column public.review.content is 'Full content of the review, formatted as Markdown.';
comment on column public.review.reviewer_id is 'Reference to an existing creator that published the review. This is useful for reviews by another author, for example.';
comment on column public.review.publication_name is 'Name of the publication the review has been published in (e.g. "New York Times", "NPR").';
comment on column public.review.published_at is 'Date the review has been published.';
comment on column public.review.url is 'URL of the page the review has been published at.';
comment on column public.review.excerpt is 'An excerpt from the full review as provided in content. Must not be longer than 200 characters.';
alter table public.review
    alter column id add generated by default as identity (
        sequence name public.review_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.review to anon;
grant all on table public.review to authenticated;
grant all on table public.review to service_role;
grant all on sequence public.review_id_seq to anon;
grant all on sequence public.review_id_seq to authenticated;
grant all on sequence public.review_id_seq to service_role;

alter table public.review
    enable row level security;

alter table only public.review
    add constraint review_pkey primary key (id);

alter table only public.review
    add constraint review_edition_id_fkey foreign key (edition_id) references public.edition (id)
        on update cascade on delete cascade;
alter table only public.review
    add constraint review_reviewer_id_fkey foreign key (reviewer_id) references public.creator (id)
        on update cascade on delete set null;
alter table only public.review
    add constraint review_updated_by_fkey foreign key (updated_by) references authentication."user" (id)
        on update cascade on delete set null;
