
  create table "public"."moderation_log" (
    "id" bigint generated by default as identity not null,
    "action_type" text not null,
    "target_type" text not null,
    "target_id" bigint not null,
    "performed_by" bigint not null,
    "details" jsonb,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."moderation_log" enable row level security;


  create table "public"."pending_ingestion" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" bigint not null,
    "upload_id" text not null,
    "s3_key" text not null,
    "checksum" text not null,
    "extracted_metadata" jsonb not null,
    "duplicate_info" jsonb not null,
    "created_at" timestamp with time zone not null default now(),
    "expires_at" timestamp with time zone not null default (now() + '24:00:00'::interval)
      );


alter table "public"."pending_ingestion" enable row level security;

CREATE INDEX idx_moderation_log_created_at ON public.moderation_log USING btree (created_at DESC);

CREATE INDEX idx_moderation_log_performed_by ON public.moderation_log USING btree (performed_by);

CREATE INDEX idx_moderation_log_target ON public.moderation_log USING btree (target_type, target_id);

CREATE INDEX idx_pending_ingestion_created ON public.pending_ingestion USING btree (created_at);

CREATE INDEX idx_pending_ingestion_expires ON public.pending_ingestion USING btree (expires_at);

CREATE INDEX idx_pending_ingestion_user ON public.pending_ingestion USING btree (user_id);

CREATE UNIQUE INDEX moderation_log_pkey ON public.moderation_log USING btree (id);

CREATE UNIQUE INDEX pending_ingestion_pkey ON public.pending_ingestion USING btree (id);

alter table "public"."moderation_log" add constraint "moderation_log_pkey" PRIMARY KEY using index "moderation_log_pkey";

alter table "public"."pending_ingestion" add constraint "pending_ingestion_pkey" PRIMARY KEY using index "pending_ingestion_pkey";

alter table "public"."moderation_log" add constraint "moderation_log_performed_by_fkey" FOREIGN KEY (performed_by) REFERENCES authentication."user"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."moderation_log" validate constraint "moderation_log_performed_by_fkey";

alter table "public"."pending_ingestion" add constraint "pending_ingestion_checksum_valid" CHECK ((checksum ~ '^[a-f0-9]{64}$'::text)) not valid;

alter table "public"."pending_ingestion" validate constraint "pending_ingestion_checksum_valid";

alter table "public"."pending_ingestion" add constraint "pending_ingestion_user_id_fkey" FOREIGN KEY (user_id) REFERENCES authentication."user"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."pending_ingestion" validate constraint "pending_ingestion_user_id_fkey";

grant delete on table "public"."moderation_log" to "anon";

grant insert on table "public"."moderation_log" to "anon";

grant references on table "public"."moderation_log" to "anon";

grant select on table "public"."moderation_log" to "anon";

grant trigger on table "public"."moderation_log" to "anon";

grant truncate on table "public"."moderation_log" to "anon";

grant update on table "public"."moderation_log" to "anon";

grant delete on table "public"."moderation_log" to "authenticated";

grant insert on table "public"."moderation_log" to "authenticated";

grant references on table "public"."moderation_log" to "authenticated";

grant select on table "public"."moderation_log" to "authenticated";

grant trigger on table "public"."moderation_log" to "authenticated";

grant truncate on table "public"."moderation_log" to "authenticated";

grant update on table "public"."moderation_log" to "authenticated";

grant delete on table "public"."moderation_log" to "service_role";

grant insert on table "public"."moderation_log" to "service_role";

grant references on table "public"."moderation_log" to "service_role";

grant select on table "public"."moderation_log" to "service_role";

grant trigger on table "public"."moderation_log" to "service_role";

grant truncate on table "public"."moderation_log" to "service_role";

grant update on table "public"."moderation_log" to "service_role";

grant delete on table "public"."pending_ingestion" to "anon";

grant insert on table "public"."pending_ingestion" to "anon";

grant references on table "public"."pending_ingestion" to "anon";

grant select on table "public"."pending_ingestion" to "anon";

grant trigger on table "public"."pending_ingestion" to "anon";

grant truncate on table "public"."pending_ingestion" to "anon";

grant update on table "public"."pending_ingestion" to "anon";

grant delete on table "public"."pending_ingestion" to "authenticated";

grant insert on table "public"."pending_ingestion" to "authenticated";

grant references on table "public"."pending_ingestion" to "authenticated";

grant select on table "public"."pending_ingestion" to "authenticated";

grant trigger on table "public"."pending_ingestion" to "authenticated";

grant truncate on table "public"."pending_ingestion" to "authenticated";

grant update on table "public"."pending_ingestion" to "authenticated";

grant delete on table "public"."pending_ingestion" to "service_role";

grant insert on table "public"."pending_ingestion" to "service_role";

grant references on table "public"."pending_ingestion" to "service_role";

grant select on table "public"."pending_ingestion" to "service_role";

grant trigger on table "public"."pending_ingestion" to "service_role";

grant truncate on table "public"."pending_ingestion" to "service_role";

grant update on table "public"."pending_ingestion" to "service_role";


