-- region Covers
create table public.cover
(
    id          bigint                                       not null,
    filename    text                                         not null,
    description text,
    media_type  text                                         not null,
    width       smallint                                     not null,
    height      smallint                                     not null,
    size        integer                                      not null,
    metadata    jsonb                    default '{}'::jsonb not null,
    updated_by  bigint,
    updated_at  timestamp with time zone,
    created_by  bigint,
    created_at  timestamp with time zone default now()       not null,
    checksum    bytea                                        not null,
    blurhash    text                                         not null,
    constraint cover_metadata_check check ((jsonb_typeof(metadata) = 'object'::text))
);
alter table public.cover
    owner to postgres;
comment on table public.cover is 'Book cover images';
comment on column public.cover.filename is 'Name, or key, of the file as persisted to the storage bucket.';
comment on column public.cover.description is 'A human-readable description of the image intended for visually impaired users.';
comment on column public.cover.media_type is 'A media type string describing the type of image file (e.g. "image/png" for a PNG file).';
comment on column public.cover.width is 'Width of the image, in pixels.';
comment on column public.cover.height is 'Height of the image, in pixels.';
comment on column public.cover.size is 'Size of the file, in bytes.';
comment on column public.cover.metadata is 'JSON object containing image file metadata.';
comment on column public.cover.checksum is 'An SHA1 hash of the file, used for ETag headers and sanity checks.';
comment on column public.cover.blurhash is 'A blurhash representation of the image; see https://blurha.sh/. Blurhashes are simple string representations of an image that can be used to render a blurred approximation of the original image.';
alter table public.cover
    alter column id add generated by default as identity (
        sequence name public.cover_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.cover to anon;
grant all on table public.cover to authenticated;
grant all on table public.cover to service_role;
grant all on sequence public.cover_id_seq to anon;
grant all on sequence public.cover_id_seq to authenticated;
grant all on sequence public.cover_id_seq to service_role;

alter table public.cover
    enable row level security;

alter table only public.cover
    add constraint cover_filename_key unique (filename);
alter table only public.cover
    add constraint cover_pkey primary key (id);

alter table only public.cover
    add constraint cover_created_by_fkey foreign key (created_by) references authentication."user" (id)
        on update cascade on delete set null;
alter table only public.cover
    add constraint cover_updated_by_fkey foreign key (updated_by) references authentication."user" (id)
        on update cascade on delete set null;
-- endregion

-- region Cover Creators
create table public.cover_creator
(
    cover_id   bigint               not null,
    creator_id bigint               not null,
    essential  boolean default true not null
);
alter table public.cover_creator
    owner to postgres;
comment on table public.cover_creator is 'Junction table for contributions to book edition covers by creators.';
alter table public.cover_creator
    alter column cover_id add generated by default as identity (
        sequence name public.cover_creator_cover_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.cover_creator to anon;
grant all on table public.cover_creator to authenticated;
grant all on table public.cover_creator to service_role;
grant all on sequence public.cover_creator_cover_id_seq to anon;
grant all on sequence public.cover_creator_cover_id_seq to authenticated;
grant all on sequence public.cover_creator_cover_id_seq to service_role;

alter table public.cover_creator
    enable row level security;

alter table only public.cover_creator
    add constraint cover_creator_pkey primary key (cover_id, creator_id);

alter table only public.cover_creator
    add constraint cover_creator_cover_id_fkey foreign key (cover_id) references public.cover (id)
        on update cascade on delete cascade;
-- endregion
