create table public.catalog
(
    id                   bigint                                         not null,
    feed_url             text                                           not null,
    title                text,
    description          text,
    image_url            text,
    url                  text,
    updated_by           bigint,
    updated_at           timestamp with time zone,
    created_at           timestamp with time zone default now()         not null,
    age_requirement      smallint                 default '0'::smallint not null,
    active               boolean                  default true          not null,
    color                public.rgb_color,
    credentials_required boolean                  default false         not null,
    constraint catalog_age_requirement_check check ((age_requirement >= 0))
);
alter table public.catalog
    owner to postgres;
comment on table public.catalog is 'An OPDS catalog to list books from.';
comment on column public.catalog.feed_url is 'The OPDS feed URL to retrieve this catalog.';
comment on column public.catalog.title is 'Name of this feed; usually retrieved from the title entry of the feed itself.';
comment on column public.catalog.description is 'Description of this feed; usually retrieved from the summary entry of the feed itself.';
comment on column public.catalog.image_url is 'An optional URL to an image representing the feed; usually retrieved from the thumbnail image link of the feed itself.';
comment on column public.catalog.url is 'The website of the feed provider.';
comment on column public.catalog.age_requirement is 'The minimum required age to access this catalog';
comment on column public.catalog.active is 'Whether this catalog is currently active and used in the app.';
alter table public.catalog
    alter column id add generated by default as identity (
        sequence name public.catalog_id_seq
        start with 1
        increment by 1
        no minvalue
        no maxvalue
        cache 1
        );

grant all on table public.catalog to anon;
grant all on table public.catalog to authenticated;
grant all on table public.catalog to service_role;
grant all on sequence public.catalog_id_seq to anon;
grant all on sequence public.catalog_id_seq to authenticated;
grant all on sequence public.catalog_id_seq to service_role;

alter table public.catalog
    enable row level security;

alter table only public.catalog
    add constraint catalog_pkey primary key (id);

alter table only public.catalog
    add constraint catalog_updated_by_fkey foreign key (updated_by) references authentication."user" (id)
        on update cascade on delete set null;
