-- API Keys for programmatic access (Basic Auth for e-readers, scripts, OPDS)

-- region API Keys
create table authentication.api_key
(
    id              bigint                                 not null,
    user_id         bigint                                 not null,
    name            character varying(100)                 not null,
    key_hash        text                                   not null,
    key_prefix      character varying(12)                  not null,
    scopes          text[]                   default '{}'  not null,
    last_used_at    timestamp with time zone,
    last_used_ip    inet,
    expires_at      timestamp with time zone,
    created_at      timestamp with time zone default now() not null,
    revoked_at      timestamp with time zone,
    rotated_from_id bigint,
    rotated_at      timestamp with time zone
);
alter table authentication.api_key
    owner to postgres;
comment on table authentication.api_key is 'API keys for programmatic access via Basic Auth.';
comment on column authentication.api_key.user_id is 'User who owns this API key.';
comment on column authentication.api_key.name is 'User-provided name to identify this key (e.g., "Kindle", "Reading Script").';
comment on column authentication.api_key.key_hash is 'SHA-256 hash of the API key. The plain text key is never stored.';
comment on column authentication.api_key.key_prefix is 'First 12 characters of the key (col_ + 8 chars) for identification in logs and UI.';
comment on column authentication.api_key.scopes is 'Permission scopes granted to this key. Empty array means all scopes.';
comment on column authentication.api_key.last_used_at is 'Timestamp of last successful authentication with this key.';
comment on column authentication.api_key.last_used_ip is 'IP address from which the key was last used.';
comment on column authentication.api_key.expires_at is 'Optional expiration timestamp. NULL means the key never expires.';
comment on column authentication.api_key.revoked_at is 'Timestamp when the key was revoked. NULL means the key is active.';
comment on column authentication.api_key.rotated_from_id is 'Reference to the previous key if this was created by rotation.';
comment on column authentication.api_key.rotated_at is 'Timestamp when this key was rotated. Used for 15-minute grace period.';
alter table authentication.api_key
    alter column id add generated by default as identity ( sequence name authentication.api_key_id_seq start with 1 increment by 1 no minvalue no maxvalue cache 1 );

grant all on table authentication.api_key to anon;
grant all on table authentication.api_key to authenticated;
grant all on table authentication.api_key to service_role;
grant all on sequence authentication.api_key_id_seq to anon;
grant all on sequence authentication.api_key_id_seq to authenticated;
grant all on sequence authentication.api_key_id_seq to service_role;

alter table authentication.api_key
    enable row level security;

alter table only authentication.api_key
    add constraint api_key_pkey primary key (id);

create index api_key_user_id_idx on authentication.api_key using btree (user_id);
create index api_key_prefix_idx on authentication.api_key using btree (key_prefix);

alter table only authentication.api_key
    add constraint api_key_user_id_fkey foreign key (user_id) references authentication."user" (id) on update cascade on delete cascade;
alter table only authentication.api_key
    add constraint api_key_rotated_from_id_fkey foreign key (rotated_from_id) references authentication.api_key (id) on update cascade on delete set null;
-- endregion
